[tool]
[tool.poetry]
name = "aiopath"
version = "0.5.7"
description = "📁 Async pathlib for Python"
license = "LGPL-3.0"
homepage = "https://github.com/alexdelorenzo/aiopath"
authors = ["Alex DeLorenzo"]
readme = "README.md"

[tool.poetry.dependencies]
python = "*"
