#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['loca']

package_data = \
{'': ['*']}

setup(name='loca',
      version='2.0.1',
      description='Local locations',
      author='Nguyễn Gia Phong',
      author_email='mcsinyx@disroot.org',
      url='https://sr.ht/~cnx/loca',
      packages=packages,
      package_data=package_data,
      python_requires='>=3.7',
     )
