
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-03T13:22:18-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "669d3452dc659a86068820e38dcd2208481ec9b1",
 "version": "2.6.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
