
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-09T13:35:38+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6779ae7755aaf9e844d63a6f63b5036fb64d9f89",
 "version": "0.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
