[tool.poetry]
name = "framework-detector"
version = "0.1.0"
description = "Detects which framework is in use in a project"
authors = ["Miles Budden <git@miles.so>"]

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^6.2.4"
black = "^21.7b0"
pre-commit = "^2.14.0"
mypy = "^0.910"
flake8 = "^3.9.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
