
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-27T09:22:06+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "3f79ab19da692ec67334b47b096301f0bb94f931",
 "version": "1.0.7rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
