
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-10T13:45:54-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "9e7f14b3f3f0272e45ce747e61d99b10601b8382",
 "version": "0.0.10rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
