
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-02T11:40:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5f4b820f93bdf1b4661a2c9487fe764347b137d5",
 "version": "0.7.0.post.dev316"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
