name: Install Prerequisites on Ubuntu

runs:
  using: composite

  steps:
    - name: Install packages
      run: |
        sudo apt-get update -q
        sudo apt-get install -yq \
             doxygen \
             libboost-dev \
             libgdal-dev \
             libgeos++-dev \
             libproj-dev \
             libsparsehash-dev \
             ruby-json \
             spatialite-bin
        if [ "$CC" = clang-6.0 ]; then sudo apt-get install -yq --no-install-suggests --no-install-recommends clang-6.0; fi
        if [ "$CC" = clang-8 ]; then sudo apt-get install -yq --no-install-suggests --no-install-recommends clang-8; fi
      shell: bash
    - name: Install from git
      run: |
        git clone --quiet --depth 1 https://github.com/mapbox/protozero.git ../protozero
      shell: bash

