
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-04T09:19:14+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4bede540c91d8b6b7ea940313921f447bf49432d",
 "version": "2505"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
