[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "apteryx"
version = "1.0.11"
description = "Utilities and useful things for Apteryx Labs"
authors = [ "apteryxlabs <matthew@apteryxlabs.com>",]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
google-api-python-client = "^2.9.0"
google-auth-httplib2 = "^0.1.0"
google-auth-oauthlib = "^0.4.4"
google-cloud-storage = "^1.39.0"
tqdm = "^4.61.1"
numpy = "^1.20.3"
ray = "^1.4.0"
pandas = "^1.2.4"
toml = "^0.10.2"
black = "^21.7b0"

[tool.poetry.dev-dependencies]
poetry-dynamic-versioning = "^0.13.0"
toml = "^0.10.2"
