
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-06T09:31:29-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d6e621c9287ac6067ba0dc9d32b360ca7b608119",
 "version": "v0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
