
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-08T11:36:12+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "44a61e73329042b2cbff5296c659382265e9ddb9",
 "version": "0.8.13a9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
