github_url = "https://github.com/ews-network/aws_cfn_kafka_admin_provider"

[tool.tbump.version]
current = "0.5.3"

regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (?:[-.](?P<rc>[\S]+))?
  '''

[tool.tbump.git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[tool.tbump.file]]
src = "setup.py"

[[tool.tbump.file]]
src = "setup.cfg"

[[tool.tbump.file]]
src = "aws_cfn_kafka_admin_provider/__init__.py"

[[tool.tbump.before_commit]]
name = "Files format"
cmd = "make conform"
