
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-08T17:40:03-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6fd658e72d882136942c57cecd6c5f6b35bbafd8",
 "version": "0.8.13b0.dev202108090712"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
