openapi: 3.0.0
info:
  title: null
  version: 0.1
paths:
  /{url+}:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: null
        tag: $latest
      parameters:
        - explode: false
          in: path
          name: url
          required: false
          style: simple