
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-04T06:36:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c0274e44710801e21a30844c9d050e058579009a",
 "version": "1.0.37"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
