
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-03T15:47:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5323bbf0282fc818ce2d3e50b65af7ea676ac4a4",
 "version": "0.2.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
