
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-03T17:56:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2be9340b6aeb2a3559d646244cd445986e336a4b",
 "version": "1.6.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
