
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-03T14:28:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6f36e3b201305cdd36ab1ebe54e76ae00edf5610",
 "version": "1.0.28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
