
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-02T12:27:05+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6549a922d7861dc3fcaf6a14ab96d0bbc3852f3c",
 "version": "0.7.0.post.dev326"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
