site_name: Reaction Network Documentation
site_description: Documentation for rxn_network
copyright: Built by The GENESIS EFRC

theme:
  name: 'material'

nav:
  - Home: index.md

site_url: https://github.com/GENESIS-EFRC/reaction-network
repo_url: https://github.com/GENESIS-EFRC/reaction-network/
markdown_extensions:
  - pymdownx.tabbed
  - admonition
  - codehilite
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - toc:
      permalink: true

plugins:
  - search
  - minify
  - mkdocstrings