[dependencies]
env_logger = "^0.9"
geo-types = "^0.7"
numpy = "0.14"
ordered-float = "^2"
rayon = "^1.5"
wkb = "0.7.1"

[dependencies.h3ron]
path = "local_dependencies/h3ron"
version = "0.12.0"

[dependencies.h3ron-h3-sys]
path = "local_dependencies/h3ron-h3-sys"
version = "0.12.0"

[dependencies.h3ron-ndarray]
path = "local_dependencies/h3ron-ndarray"
version = "0.12.0"

[dependencies.ndarray]
features = ["rayon"]
version = "0.15"

[dependencies.pyo3]
features = ["extension-module", "abi3", "abi3-py36"]
version = "0.14"

[lib]
crate-type = ["cdylib"]
name = "h3ronpy"

[package]
authors = ["Nico Mandery <nico@nmandery.net>"]
description = "python bindings for h3ron"
edition = "2018"
homepage = "https://github.com/nmandery/h3ron"
keywords = ["geo", "spatial", "h3", "ndarray", "numpy", "python"]
license = "MIT"
name = "h3ronpy"
readme = "README.md"
repository = "https://github.com/nmandery/h3ron"
version = "0.12.0"
[package.metadata.maturin]
classifiers = ["Programming Language :: Python :: 3", "Topic :: Scientific/Engineering :: GIS", "License :: OSI Approved :: MIT License"]
requires-dist = ["numpy", "geopandas>=0.8", "h3>=3.7", "Shapely>=1.7"]
