"""v2

Revision ID: a775428a9951
Revises: 37e707769b36
Create Date: 2021-08-09 01:34:05.211047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a775428a9951'
down_revision = '37e707769b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('created_ts', sa.Integer(), nullable=False),
    sa.Column('last_modified_ts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address', 'url', 'method', name='un_requests_address_url_method')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###
