[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 120

[tool.coverage.report]
fail_under = 79

[tool.coverage.run]
branch = true
omit = [
    ".venv/*",
]

[tool.isort]
line_length = 120
profile = "black"

[tool.mypy]
show_error_codes = true
strict = true

[tool.poetry]
name = "vcard"
version = "0.14.1"
description = "vCard validator, class and utility functions"
authors = ["Victor Engmark <victor@engmark.name>"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.6"
python-dateutil = "*"

[tool.poetry.dev-dependencies]
black = "*"
coverage = "*"
gitlint = "*"
isort = "*"
language-formatters-pre-commit-hooks = "*"
mock = "*"
mypy = "*"
pre-commit = "*"
pylint = "*"
shellcheck-py = "*"
twine = "*"

[tool.pylint.MASTER]
disable = [
    "duplicate-code",
    "missing-docstring",
]
load-plugins = [
    "pylint.extensions.mccabe",
]
max-complexity = 10
max-line-length = 120
