#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['workedon']

package_data = \
{'': ['*']}

setup(name='workedon',
      version='0.1.0',
      description='Top-level package for workedon.',
      author=None,
      author_email='viseshrp <viseshrprasad@gmail.com>',
      url=None,
      packages=packages,
      package_data=package_data,
     )
