
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e2837deb8647119c37338da819c42b4da492c64d",
 "version": "1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
