
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-03T02:04:14-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "dbe18c038ded69c46467fdf2238f399df3f74345",
 "version": "2021.8.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
