
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-08T14:04:29+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d19cb4bad61876b135f974bbcf95cea3430cb20",
 "version": "1.78"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
