[tool.poetry]
name = "state-signals"
version = "0.1.1"
description = "Package for easy management of state/event signal publishing, subscribing, and responding"

license = "GPL"

authors = [
    "Mustafa Eyceoz <meyceoz@redhat.com>"
]

readme = 'README.md'  # Markdown files are supported

repository = "https://github.com/Maxusmusti/state-signals"
homepage = "https://github.com/Maxusmusti/state-signals"

keywords = ['state', 'event', 'signal', 'publish', 'subscribe']

[tool.poetry.dependencies]
python = "~2.7 || ^3.2"  # Compatible python versions must be declared here
redis = "^3.5"
dataclasses = "^0.8"