
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-10T11:12:35+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "fd879d521510a866551ee6d1af63bb28d0b1b2cb",
 "version": "0.7.0.post.dev338"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
