
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-03T17:18:12+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "426c15b9e4895bdba449be3c63168b5179a34202",
 "version": "0.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
