
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-04T15:08:26+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "fd0bce322641e2157f2dcff14d90b09dcc1d4396",
 "version": "0.21.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
