
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-02T14:50:06-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "5178fe39921a41d5fa6d5553294c9bc1a1453a10",
 "version": "2021.8.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
