
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-03T05:53:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1de351f0427755c318af61e9701f2236ec5e9465",
 "version": "1.0.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
