
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-04T03:18:39+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "89728f7a2a490741676648d649a253f5012bae7a",
 "version": "1.15.0.post.dev251"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
