
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-03T19:26:13-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b53bfd4b30c5bae420ac86247256a2c98208b04",
 "version": "2021.8.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
