---
# These configuration values must be stored in the user's config.yml.
MYSQL_ROOT_PASSWORD: "{{ 8|random_string }}"
OPENCART_MYSQL_PASSWORD: "{{ 8|random_string }}"
ID: "{{ 24|random_string }}"

# This must be defined early
STORE_HOST: "www.myopencart.com"

# The following are default values
RUN_CADDY: true
RUN_OPENCART: true
ENABLE_HTTPS: false
RUN_MYSQL: true
RUN_SMTP: true
CONTACT_EMAIL: "sales@{{ STORE_HOST }}"
OPENCART_AWS_ACCESS_KEY: ""
OPENCART_AWS_SECRET_ACCESS_KEY: ""
DEV_PROJECT_NAME: "peddler_dev"
DOCKER_REGISTRY: "docker.io/"
DOCKER_IMAGE_CADDY: "{{ DOCKER_REGISTRY }}caddy:2.2.1"
DOCKER_IMAGE_OPENCART: "{{ DOCKER_REGISTRY }}alto9/opencart:{{ PEDDLER_VERSION }}"
DOCKER_IMAGE_OPENCART_DEV: "{{ DOCKER_REGISTRY }}alto9/opencart-dev:{{ PEDDLER_VERSION }}"
DOCKER_IMAGE_MYSQL: "{{ DOCKER_REGISTRY }}mysql:5.7.32"
DOCKER_IMAGE_NGINX: "{{ DOCKER_REGISTRY }}nginx:1.13"
DOCKER_IMAGE_SMTP: "{{ DOCKER_REGISTRY }}namshi/smtp:latest"
LOCAL_PROJECT_NAME: "peddler_local"
K8S_NAMESPACE: "opencart"
OPENCART_MYSQL_DATABASE: "opencart"
OPENCART_MYSQL_USERNAME: "opencart"
OPENCART_ADMIN_USERNAME: "admin"
OPENCART_ADMIN_PASSWORD: "opencart"
MYSQL_HOST: "mysql"
MYSQL_PORT: 3306
MYSQL_ROOT_USERNAME: "root"
NGINX_HTTP_PORT: 80
PLATFORM_NAME: "My OpenCart Shop"
PLUGINS: []
SMTP_HOST: "smtp"
SMTP_PORT: 25
SMTP_USERNAME: ""
SMTP_PASSWORD: ""
SMTP_USE_TLS: false
SMTP_USE_SSL: false