name: "Code Analysis"

on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]
    paths:
      - '**.py'
      - '.github/codeql/**'
      - '.github/workflows/code-analysis.yml'

  schedule:
    - cron: '0 8 * * 6'

permissions:
  contents: read
  security-events: write

jobs:
  CodeQL:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        config-file: ./.github/codeql/codeql-config.yml

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
