
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-03T11:05:01+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "8b62baa14b53b97c2fdb79c5ed77ba9f798c6581",
 "version": "0.2.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
