[tool.poetry]
name = "elz-py-tools"
version = "0.1.4"
description = "Python components compliant with Synaptix framework"
authors = ["Hervé <herve.descombe@elzeard.co>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://gitlab.com/elzeard/elz-py-tools"
repository = "https://gitlab.com/elzeard/elz-py-tools"
classifiers = [
    "Environment :: Console",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
include = [
    "LICENSE"
]

[tool.poetry.dependencies]
python = "^3.8"
aio-pika = "^6.8.0"
pymongo = "^3.11.4"
elasticsearch = "^7.13.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
