[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ["py37"]

[tool.isort]
profile = "black"
force_sort_within_sections = true
include_trailing_comma = true
line_length = 79

[tool.pyright]
exclude = ['venv']
typeCheckingMode = "strict"
pythonVersion = "3.7"
reportPrivateUsage = false
