
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-09T20:14:06-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "cf381ac874e18b0860c0685a593c560d4572eebb",
 "version": "0.9.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
