[tool.poetry]
name = "gitfix"
version = "0.2.2"
description = "Command-line tool to help you recover from a broken git state."
authors = ["Lucas Melin <lucas.melin@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/lucasmelin/gitfix"
homepage = "https://github.com/lucasmelin/gitfix"
keywords = ["git"]
classifiers = ["Topic :: Software Development :: Version Control :: Git", "Topic :: Utilities"]

[tool.poetry.scripts]
gitfix = 'gitfix.main:main'

[tool.poetry.dependencies]
python = "^3.9"
blessed = "^1.18.1"
rich = "^10.6.0"

[tool.poetry.dev-dependencies]
coverage = {extras = ["toml"], version = "^5.5"}
black = "^21.6b0"
flake8 = "^3.9.2"
flake8-bandit = "^2.1.2"
flake8-black = "^0.2.1"
flake8-bugbear = "^21.4.3"
flake8-comprehensions = "^3.5.0"
flake8-docstrings = "^1.6.0"
flake8-import-order = "^0.18.1"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
pytest-mock = "^3.6.1"
safety = "^1.10.3"
xdoctest = "^0.15.5"
rope = "^0.19.0"
nox = "^2021.6.12"
pep8-naming = "^0.11.1"
bandit = "^1.7.0"
pyinstaller = "^4.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
