
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-10T14:08:49-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "67a27682308a376f4213ef3a2b7225d96e031d02",
 "version": "4.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
