
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-05T17:01:49-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9c5b966bf6952925d2ea8c5dbc2d3cfdb8ea2497",
 "version": "0.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
