
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-03T05:48:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8058ce25d0e1361529221e7c83cc1c0e3c000c5e",
 "version": "1.0.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
