[project]
name = "python-glimmer"
version = "1.7.3"
description = ""
readme = "README.md"
dependencies = [ "requests~=2.25", "rich~=10.0", "click~=7.1", "zoomeye~=2.0", "shodan~=1.25", "func-timeout~=4.3",]
requires-python = ">=3.6"
dynamic = [ "classifiers",]
[[project.authors]]
name = "WAY29"
email = "1162410187@qq.com"

[build-system]
requires = [ "pdm-pep517",]
build-backend = "pdm.pep517.api"

[project.license]
text = "MIT"

[project.urls]
homepage = "https://github.com/WAY29/glimmer"

[project.scripts]
glimmer = "glimmer.main:main"

[tool.pdm.scripts.publish]
shell = "pdm build && twine upload dist/*"

[tool.pdm.scripts.tree]
shell = "pdm list --graph"
