# https://packaging.python.org/tutorials/packaging-projects/
# https://python-packaging.readthedocs.io/en/latest/
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
