#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['requests >= 2.25']

setup(name='gotify',
      version='0.2.0',
      description='Access your gotify server.',
      author='d-k-bo',
      author_email='dkbo@mail.de',
      url='https://github.com/d-k-bo/python-gotify',
      py_modules=['gotify'],
      install_requires=install_requires,
      python_requires='>=3.8',
     )
