
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-06T03:50:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "66ac492f34c96222ec7ae81c1451fecf403c6434",
 "version": "1.15.0.post.dev263"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
