
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-04T16:19:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "03524667bbb660c2e70775021e62b546b7ae2c00",
 "version": "0.26.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
