
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-08T00:27:03+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6e1528a48fcca799efc518452105fc867e578cc5",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
