
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-04T12:46:55+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "35c55c5b774727a45ce6b671de55c5fc8cf72e1b",
 "version": "v0.6.4a4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
