
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-06T22:36:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1f98d26b0c07896d2f4ad2086d0eb57d13717e9f",
 "version": "v0.1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
