[[bench]]
harness = false
name = "convert_dataset_r"

[dependencies]
geo-types = "^0.7"
log = "^0.4"
rayon = "^1.5"

[dependencies.h3ron]
path = "../h3ron"
version = "0.12.0"

[dependencies.ndarray]
features = ["rayon"]
version = "^0.15"

[dev-dependencies]
approx = "^0.5"
env_logger = "^0.9"

[dev-dependencies.criterion]
features = ["html_reports"]
version = "^0.3"

[dev-dependencies.gdal]
features = ["array"]
version = "^0.9"

[package]
authors = ["Nico Mandery <nico@nmandery.net>"]
description = "Integration with the ndarray crate to generate H3 cells from raster data (using gdal, ...)"
edition = "2018"
homepage = "https://github.com/nmandery/h3ron"
keywords = ["geo", "spatial", "h3", "ndarray"]
license = "MIT"
name = "h3ron-ndarray"
readme = "../README.md"
repository = "https://github.com/nmandery/h3ron"
version = "0.12.0"
