#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['lockout']

package_data = \
{'': ['*']}

install_requires = \
['flit_core >=2,<4', 'scikit-learn', 'tqdm', 'pandas', 'matplotlib', 'numpy']

setup(name='lockout',
      version='0.1.5',
      description='Lockout: Sparse Regularization of Neural Networks',
      author='Wilmer Arbelo',
      author_email='wilmer.arbelogonzalez@ucsf.edu',
      url='https://github.com/warbelo/Lockout',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
     )
