
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-02T12:53:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c02b280c7203b5adc1453998808aad3d62c867eb",
 "version": "0.7.0.post.dev332"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
