# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2021-06-28T10:59:42+00:00

from __future__ import annotations

from kelvin.sdk.client.data_model import DataModelBase


class TimeMicro(DataModelBase):
    """
    TimeMicro object.

    Parameters
    ----------

    """
