[build-system]
requires = ["setuptools >= 30.3.0", "wheel"]


[tool.black]
target-version = ["py37", "py38", "py39"]
line-length = 100


[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100
known_tests = "tests"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,TESTS,LOCALFOLDER"
lines_after_imports = 2
lines_between_sections = 1


[tool.mypy]
warn_unused_configs = true


[[tool.mypy.overrides]]
module = [
    "pymemcache",
    "redis.sentinel",
    "rediscluster",
]
ignore_missing_imports = true
