
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-09T12:24:54-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "59eced7d0b8c738abc93e23fa1c639dd45ffd803",
 "version": "4.12.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
