#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['avss']

package_data = \
{'': ['*']}

setup(name='avss',
      version='0.0.1',
      description='This is a test.',
      author=None,
      author_email='Victor Krook <victorkrook96@gmail.com>',
      url=None,
      packages=packages,
      package_data=package_data,
     )
