[tool.poetry]
name = "poetry-bundla-plugin"
version = "0.1.3"
description = "Poetry plugin to bundle projects into various formats"
authors = ["Sébastien Eustace <sebastien@eustace.io>", "jtzero <jtzero511@gmail.com>"]
license = "MIT"
readme = "README.md"

packages = [
    { include = "poetry_bundle_plugin", from = "src" }
]

include = [
    { path = "tests", format = "sdist" }
]

[tool.poetry.dependencies]
python = "^3.6"
poetry = "1.2.0a2"

[tool.poetry.dev-dependencies]
black = { version = "^21.4b1", python = "^3.6.2"}
isort = "^5.8.0"
pre-commit = { version = "^2.6", python = "^3.6.1" }
pytest = "^6.2.3"
pytest-mock = "^3.6.1"

[tool.poetry.plugins."poetry.application.plugin"]
poetry-bundla-plugin = "poetry_bundle_plugin.plugin:BundleApplicationPlugin"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
force_single_line = true
atomic = true
include_trailing_comma = true
lines_after_imports = 2
lines_between_types = 1
use_parentheses = true


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
