
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-04T15:15:02-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "77d86bd05897ada3f10a24e51d4306c736038292",
 "version": "1.4.1rc9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
