input_info:
  input_source: MUST_FILL
  input_name: genotype
  input_type: omics

input_type_info:
  model_type: genome-local-net
  na_augment_perc: 0.4
  na_augment_prob: 1.0
  snp_file: MUST_FILL

model_config:
  rb_do: 0.5
  channel_exp_base: 2
  layers:
    - 2
  kernel_width: 8
