
country_data = {
    'Afghanistan': ('AF', 'AFG', 4),
    'Aland Islands': ('AX', 'ALA', 248),
    'Albania': ('AL', 'ALB', 8),
    'Algeria': ('DZ', 'DZA', 12),
    'American Samoa': ('AS', 'ASM', 16),
    'Andorra': ('AD', 'AND', 20),
    'Angola': ('AO', 'AGO', 24),
    'Anguilla': ('AI', 'AIA', 660),
    'Antarctica': ('AQ', 'ATA', 10),
    'Antigua And Barbuda': ('AG', 'ATG', 28),
    'Argentina': ('AR', 'ARG', 32),
    'Armenia': ('AM', 'ARM', 51),
    'Aruba': ('AW', 'ABW', 533),
    'Australia': ('AU', 'AUS', 36),
    'Austria': ('AT', 'AUT', 40),
    'Azerbaijan': ('AZ', 'AZE', 31),
    'Bahamas': ('BS', 'BHS', 44),
    'Bahrain': ('BH', 'BHR', 48),
    'Bangladesh': ('BD', 'BGD', 50),
    'Barbados': ('BB', 'BRB', 52),
    'Belarus': ('BY', 'BLR', 112),
    'Belgium': ('BE', 'BEL', 56),
    'Belize': ('BZ', 'BLZ', 84),
    'Benin': ('BJ', 'BEN', 204),
    'Bermuda': ('BM', 'BMU', 60),
    'Bhutan': ('BT', 'BTN', 64),
    'Bolivia': ('BO', 'BOL', 68),
    'Bonaire, Sint Eustatius And Saba': ('BQ', 'BES', 535),
    'Bosnia And Herzegovina': ('BA', 'BIH', 70),
    'Botswana': ('BW', 'BWA', 72),
    'Bouvet Island': ('BV', 'BVT', 74),
    'Brazil': ('BR', 'BRA', 76),
    'British Indian Ocean Territory': ('IO', 'IOT', 86),
    'Brunei': ('BN', 'BRN', 96),
    'Bulgaria': ('BG', 'BGR', 100),
    'Burkina Faso': ('BF', 'BFA', 854),
    'Burundi': ('BI', 'BDI', 108),
    'Cabo Verde': ('CV', 'CPV', 132),
    'Cambodia': ('KH', 'KHM', 116),
    'Cameroon': ('CM', 'CMR', 120),
    'Canada': ('CA', 'CAN', 124),
    'Cayman Islands': ('KY', 'CYM', 136),
    'Central African Republic': ('CF', 'CAF', 140),
    'Chad': ('TD', 'TCD', 148),
    'Chile': ('CL', 'CHL', 152),
    'China': ('CN', 'CHN', 156),
    'Christmas Island': ('CX', 'CXR', 162),
    'Cocos (Keeling) Islands': ('CC', 'CCK', 166),
    'Colombia': ('CO', 'COL', 170),
    'Comoros': ('KM', 'COM', 174),
    'Cook Islands': ('CK', 'COK', 184),
    'Costa Rica': ('CR', 'CRI', 188),
    "Cote D'Ivoire": ('CI', 'CIV', 384),
    'Croatia': ('HR', 'HRV', 191),
    'Cuba': ('CU', 'CUB', 192),
    'Curacao': ('CW', 'CUW', 531),
    'Cyprus': ('CY', 'CYP', 196),
    'Czech Republic': ('CZ', 'CZE', 203),
    'Democratic Republic Of The Congo': ('CD', 'COD', 180),
    'Denmark': ('DK', 'DNK', 208),
    'Djibouti': ('DJ', 'DJI', 262),
    'Dominica': ('DM', 'DMA', 212),
    'Dominican Republic': ('DO', 'DOM', 214),
    'Ecuador': ('EC', 'ECU', 218),
    'Egypt': ('EG', 'EGY', 818),
    'El Salvador': ('SV', 'SLV', 222),
    'Equatorial Guinea': ('GQ', 'GNQ', 226),
    'Eritrea': ('ER', 'ERI', 232),
    'Estonia': ('EE', 'EST', 233),
    'Eswatini': ('SZ', 'SWZ', 748),
    'Ethiopia': ('ET', 'ETH', 231),
    'Falkland Islands': ('FK', 'FLK', 238),
    'Faroe Islands': ('FO', 'FRO', 234),
    'Fiji': ('FJ', 'FJI', 242),
    'Finland': ('FI', 'FIN', 246),
    'France': ('FR', 'FRA', 250),
    'French Guiana': ('GF', 'GUF', 254),
    'French Polynesia': ('PF', 'PYF', 258),
    'French Southern Territories': ('TF', 'ATF', 260),
    'Gabon': ('GA', 'GAB', 266),
    'Gambia': ('GM', 'GMB', 270),
    'Georgia': ('GE', 'GEO', 268),
    'Germany': ('DE', 'DEU', 276),
    'Ghana': ('GH', 'GHA', 288),
    'Gibraltar': ('GI', 'GIB', 292),
    'Greece': ('GR', 'GRC', 300),
    'Greenland': ('GL', 'GRL', 304),
    'Grenada': ('GD', 'GRD', 308),
    'Guadeloupe': ('GP', 'GLP', 312),
    'Guam': ('GU', 'GUM', 316),
    'Guatemala': ('GT', 'GTM', 320),
    'Guernsey': ('GG', 'GGY', 831),
    'Guinea': ('GN', 'GIN', 324),
    'Guinea-Bissau': ('GW', 'GNB', 624),
    'Guyana': ('GY', 'GUY', 328),
    'Haiti': ('HT', 'HTI', 332),
    'Heard Island And McDonald Islands': ('HM', 'HMD', 334),
    'Honduras': ('HN', 'HND', 340),
    'Hong Kong': ('HK', 'HKG', 344),
    'Hungary': ('HU', 'HUN', 348),
    'Iceland': ('IS', 'ISL', 352),
    'India': ('IN', 'IND', 356),
    'Indonesia': ('ID', 'IDN', 360),
    'Iran': ('IR', 'IRN', 364),
    'Iraq': ('IQ', 'IRQ', 368),
    'Ireland': ('IE', 'IRL', 372),
    'Isle Of Man': ('IM', 'IMN', 833),
    'Israel': ('IL', 'ISR', 376),
    'Italy': ('IT', 'ITA', 380),
    'Jamaica': ('JM', 'JAM', 388),
    'Japan': ('JP', 'JPN', 392),
    'Jersey': ('JE', 'JEY', 832),
    'Jordan': ('JO', 'JOR', 400),
    'Kazakhstan': ('KZ', 'KAZ', 398),
    'Kenya': ('KE', 'KEN', 404),
    'Kiribati': ('KI', 'KIR', 296),
    'Kuwait': ('KW', 'KWT', 414),
    'Kyrgyzstan': ('KG', 'KGZ', 417),
    'Laos': ('LA', 'LAO', 418),
    'Latvia': ('LV', 'LVA', 428),
    'Lebanon': ('LB', 'LBN', 422),
    'Lesotho': ('LS', 'LSO', 426),
    'Liberia': ('LR', 'LBR', 430),
    'Libya': ('LY', 'LBY', 434),
    'Liechtenstein': ('LI', 'LIE', 438),
    'Lithuania': ('LT', 'LTU',440),
    'Luxembourg': ('LU', 'LUX', 442),
    'Macao': ('MO', 'MAC', 446),
    'North Korea': ('KP', 'PRK', 408),
    'Macedonia': ('MK', 'MKD', 807),
    'Madagascar': ('MG', 'MDG', 450),
    'Malawi': ('MW', 'MWI', 454),
    'Malaysia': ('MY', 'MYS', 458),
    'Maldives': ('MV', 'MDV', 462),
    'Mali': ('ML', 'MLI', 466),
    'Malta': ('MT', 'MLT', 470),
    'Marshall Islands': ('MH', 'MHL', 584),
    'Martinique': ('MQ', 'MTQ', 474),
    'Mauritania': ('MR', 'MRT', 478),
    'Mauritius': ('MU', 'MUS', 480),
    'Mayotte': ('YT', 'MYT', 175),
    'Mexico': ('MX', 'MEX', 484),
    'Micronesia': ('FM', 'FSM', 583),
    'Moldova': ('MD', 'MDA', 498),
    'Monaco': ('MC', 'MCO', 492),
    'Mongolia': ('MN', 'MNG', 496),
    'Montenegro': ('ME', 'MNE', 499),
    'Montserrat': ('MS', 'MSR', 500),
    'Morocco':('MA', 'MAR', 504),
    'Mozambique': ('MZ', 'MOZ', 508),
    'Myanmar': ('MM', 'MMR', 104),
    'Namibia': ('NA', 'NAM', 516),
    'Nauru': ('NR', 'NRU', 520),
    'Nepal': ('NP', 'NPL', 524),
    'Netherlands': ('NL', 'NLD', 528),
    'New Caledonia': ('NC', 'NCL', 540),
    'New Zealand': ('NZ', 'NZL', 554),
    'Nicaragua': ('NI', 'NIC', 558),
    'Niger': ('NE', 'NER', 562),
    'Nigeria': ('NG', 'NGA',566),
    'Niue': ('NU', 'NIU', 570),
    'Norfolk Island': ('NF', 'NFK', 574),
    'Northern Mariana Islands': ('MP', 'MNP', 580),
    'Norway': ('NO', 'NOR', 578),
    'Oman': ('OM', 'OMN', 512),
    'Pakistan': ('PK', 'PAK', 586),
    'Palau': ('PW', 'PLW', 585),
    'Palestine': ('PS', 'PSE', 275),
    'Panama': ('PA', 'PAN', 591),
    'Papua New Guinea': ('PG', 'PNG', 598),
    'Paraguay': ('PY', 'PRY',600),
    'Peru': ('PE', 'PER', 604),
    'Philippines': ('PH', 'PHL', 608),
    'Pitcairn': ('PN', 'PCN', 612),
    'Poland': ('PL', 'POL', 616),
    'Portugal': ('PT', 'PRT', 620),
    'Puerto Rico': ('PR', 'PRI', 630),
    'Qatar': ('QA', 'QAT', 634),
    'Republic Of The Congo': ('CG', 'COG', 178),
    'Reunion': ('RE', 'REU', 638),
    'Romania': ('RO', 'ROU', 642),
    'Russia': ('RU', 'RUS', 643),
    'Rwanda': ('RW', 'RWA', 646),
    'Saint Barthelemy': ('BL', 'BLM', 652),
    'Saint Helena, Ascension And Tristan Da Cunha': ('SH', 'SHN', 654),
    'Saint Kitts and Nevis': ('KN', 'KNA', 659),
    'Saint Lucia': ('LC', 'LCA', 662),
    'Saint Martin': ('MF', 'MAF', 663),
    'Saint Pierre And Miquelon': ('PM', 'SPM', 666),
    'Saint Vincent And The Grenadines': ('VC', 'VCT', 670),
    'Samoa': ('WS', 'WSM', 882),
    'San Marino': ('SM', 'SMR', 674),
    'Sao Tome And Principe': ('ST', 'STP', 678),
    'Saudi Arabia': ('SA', 'SAU', 682),
    'Senegal': ('SN', 'SEN', 686),
    'Serbia': ('RS', 'SRB', 688),
    'Seychelles': ('SC', 'SYC', 690),
    'Sierra Leone': ('SL', 'SLE', 694),
    'Singapore': ('SG', 'SGP', 702),
    'Sint Maarten': ('SX', 'SXM', 534),
    'Slovakia': ('SK', 'SVK', 703),
    'Slovenia': ('SI', 'SVN', 705),
    'Solomon Islands': ('SB', 'SLB', 90),
    'Somalia': ('SO', 'SOM', 706),
    'South Africa': ('ZA', 'ZAF', 710),
    'South Georgia And The South Sandwich Islands': ('GS', 'SGS', 239),
    'South Korea': ('KR', 'KOR', 410),
    'South Sudan': ('SS', 'SSD', 728),
    'Spain': ('ES', 'ESP', 724),
    'Sri Lanka': ('LK', 'LKA', 144),
    'Sudan': ('SD', 'SDN', 729),
    'Suriname': ('SR', 'SUR', 740),
    'Svalbard And Jan Mayen': ('SJ', 'SJM', 744),
    'Sweden': ('SE', 'SWE', 752),
    'Switzerland': ('CH', 'CHE', 756),
    'Syria': ('SY', 'SYR', 760),
    'Taiwan': ('TW', 'TWN', 158),
    'Tajikistan': ('TJ', 'TJK',762),
    'Tanzania': ('TZ', 'TZA', 834),
    'Thailand': ('TH', 'THA', 764),
    'Timor-Leste': ('TL', 'TLS', 626),
    'Togo': ('TG', 'TGO', 768),
    'Tokelau': ('TK', 'TKL', 772),
    'Tonga': ('TO', 'TON', 776),
    'Trinidad And Tobago': ('TT', 'TTO', 780),
    'Tunisia': ('TN', 'TU', 788),
    'Turkey': ('TR', 'TUR', 792),
    'Turkmenistan': ('TM', 'TKM', 795),
    'Turks And Caicos Islands': ('TC', 'TCA', 796),
    'Tuvalu': ('TV', 'TUV', 798),
    'Uganda': ('UG', 'UGA', 8),
    'Ukraine': ('UA', 'UKR', 804),
    'United Arab Emirates': ('AE', 'ARE', 784),
    'United Kingdom': ('GB', 'GBR', 826),
    'United States Minor Outlying Islands': ('UM', 'UMI', 581),
    'United States Of America': ('US', 'USA', 840),
    'Uruguay': ('UY', 'URY', 858),
    'Uzbekistan': ('UZ', 'UZB', 860),
    'Vanuatu': ('VU', 'VUT', 548),
    'Vatican City': ('VA', 'VAT', 336),
    'Venezuela': ('VE', 'VEN', 862),
    'Vietnam': ('VN', 'VNM', 704),
    'Virgin Islands (British)': ('VG', 'VGB', 92),
    'Virgin Islands (U.S)': ('VI', 'VIR', 850),
    'Wallis And Futuna': ('WF', 'WLF', 876),
    'Western Sahara': ('EH', 'ESH', 732),
    'Yemen': ('YE', 'YEM', 887),
    'Zambia': ('ZM', 'ZMB', 894),
    'Zimbabwe': ('ZW', 'ZWE', 716)
}

currency_data = {
    'Afghanistan': ('Asia', 'Afghanistani Afghani', 'AFN', '௹'),
    'Albania': ('Europe', 'Albanian Lek', 'ALL', 'Lek'),
    'Algeria': ('Africa', 'Algerian Dinar', 'DZD', 'دج'),
    'Andorra': ('Europe', 'European Euro', 'EUR', '€'),
    'Angola': ('Africa', 'Angolan Kwanza', 'AOA', 'Kz'),
    'Antigua And Barbuda': ('North America', 'East Caribbean Dollar', 'XCD', '$'),
    'Argentina': ('South America', 'Argentine Peso', 'ARS', '$'),
    'Armenia': ('Europe', 'Armenian Dram', 'AMD', 'դր.'),
    'Australia': ('Australia and Oceania', 'Australian Dollar', 'AUD', '$'),
    'Austria': ('Europe', 'European Euro', 'EUR', '€'),
    'Azerbaijan': ('Europe', 'Azerbaijani Manat', 'AZN', '₼'),
    'Bahamas': ('North America', 'Bahamian Dollar', 'BSD', '$'),
    'Bahrain': ('Asia', 'Bahraini Dinar', 'BHD', '.د.ب'),
    'Bangladesh': ('Asia', 'Bangladeshi Taka', 'BDT', '৳'),
    'Barbados': ('North America', 'Barbados Dollar', 'BBD', '$'),
    'Belarus': ('Europe', 'Belarusian Ruble', 'BYR', 'Br'),
    'Belgium': ('Europe', 'European Euro', 'EUR', '€'),
    'Belize': ('North America', 'Belize Dollar', 'BZD', 'BZ$'),
    'Benin': ('Africa', 'West African CFA', 'XOF', 'CFA'),
    'Bhutan': ('Asia', 'Bhutanese Ngultrum', 'BTN', 'Nu.'),
    'Bolivia': ('South America', 'Bolivian Boliviano', 'BOB', '$b'),
    'Bosnia And Herzegovina': ('Europe',
                               'Bosnia-Herzegovina Convertible Mark',
                               'BAM',
                               'KM'),
    'Botswana': ('Africa', 'Botswana Pula', 'BWP', 'P'),
    'Brazil': ('South America', 'Brazilian Real', 'BRL', 'R$'),
    'Brunei': ('Asia', 'Brunei Dollar', 'BND', '$'),
    'Bulgaria': ('Europe', 'Bulgarian Lev', 'BGN', 'лв'),
    'Burkina Faso': ('Africa', 'West African CFA', 'XOF', 'CFA'),
    'Burundi': ('Africa', 'Burundian Franc', 'BIF', 'FBu'),
    'Cabo Verde': ('Africa', 'Cape Verde Escudo', 'CVE', '$'),
    'Cambodia': ('Asia', 'Cambodian Riel', 'KHR', '៛'),
    'Cameroon': ('Africa', 'Central African CFA', 'XAF', 'FCFA'),
    'Canada': ('North America', 'Canadian Dollar', 'CAD', '$'),
    'Central African Republic': ('Africa',
                                 'Central African CFA',
                                 'XAF',
                                 'FCFA'),
    'Chad': ('Africa', 'Central African CFA', 'XAF', 'FCFA'),
    'Chile': ('South America', 'Chilean Peso', 'CLP', '$'),
    'China': ('Asia', 'Chinese Yuan Renminbi', 'CNY', '¥'),
    'Colombia': ('South America', 'Colombian Peso', 'COP', '$'),
    'Comoros': ('Africa', 'Comorian Franc', 'KMF', 'CF'),
    'Costa Rica': ('North America', 'Costa Rican Colon', 'CRC', '₡'),
    "Cote D'Ivoire": ('Africa', 'West African CFA', 'XOF', 'CFA'),
    'Croatia': ('Europe', 'Croatian Kuna', 'HRK', 'kn'),
    'Cuba': ('North America', 'Cuban Convertible Peso', 'CUC', '$'),
    'Cyprus': ('Europe', 'Cypriot Pound', 'CYP', '£'),
    'Czech Republic': ('Europe', 'Czech Koruna', 'CZK', 'Kč'),
    'Democratic Republic Of The Congo': ('Africa', 'Congolese franc', 'CDF', 'FC'),
    'Denmark': ('Europe', 'Danish Krone', 'DKK', 'kr.'),
    'Djibouti': ('Africa', 'Djiboutian Franc', 'DJF', 'Fdj'),
    'Dominica': ('North America', 'East Caribbean Dollar', 'XCD', '$'),
    'Dominican Republic': ('North America', 'Dominican Peso', 'DOP', 'RD$'),
    'Ecuador': ('South America', 'United States Dollar', 'USD', '$'),
    'Egypt': ('Africa', 'Egyptian Pound', 'EGP', '£'),
    'El Salvador': ('North America', 'United States Dollar', 'USD', '$'),
    'Equatorial Guinea': ('Africa', 'Central African CFA', 'XAF', 'FCFA'),
    'Eritrea': ('Africa', 'Eritrean Nakfa', 'ERN', 'ናቕፋ'),
    'Estonia': ('Europe', 'Estonian Kroon', 'EEK', 'EEK'),
    'Eswatini': ('Africa', 'Swazi Lilangeni', 'SZL', 'E'),
    'Ethiopia': ('Africa', 'Ethiopian Birr', 'ETB', 'ብር'),
    'Fiji': ('Australia and Oceania', 'Fiji Dollar', 'FJD', '$'),
    'Finland': ('Europe', 'European Euro', 'EUR', '€'),
    'France': ('Europe', 'European Euro', 'EUR', '€'),
    'Gabon': ('Africa', 'Central African CFA', 'XAF', 'FCFA'),
    'Gambia': ('Africa', 'Gambian Dalasi', 'GMD', 'D'),
    'Georgia': ('Europe', 'Georgian Lari', 'GEL', 'ლ'),
    'Germany': ('Europe', 'European Euro', 'EUR', '€'),
    'Ghana': ('Africa', 'Ghanaian Cedi', 'GHC', 'GH₵'),
    'Greece': ('Europe', 'European Euro', 'EUR', '€'),
    'Grenada': ('North America', 'East Caribbean Dollar', 'XCD', '$'),
    'Guatemala': ('North America', 'Guatemalan Quetzal', 'GTQ', 'Q'),
    'Guinea': ('Africa', 'Guinean Franc', 'GNF', 'FG'),
    'Guinea-Bissau': ('Africa', 'West African CFA', 'XOF', 'CFA'),
    'Guyana': ('South America', 'Guyanese Dollar', 'GYD', '$'),
    'Haiti': ('North America', 'Haitian Gourde', 'HTG', 'G'),
    'Honduras': ('North America', 'Honduran Lempira', 'HNL', 'L'),
    'Hungary': ('Europe', 'Hungarian Forint', 'HUF', 'Ft'),
    'Iceland': ('Europe', 'Icelandic Krona', 'ISK', 'kr'),
    'India': ('Asia', 'Indian Rupee', 'INR', '₹'),
    'Indonesia': ('Asia', 'Indonesian Rupiah', 'IDR', 'Rp'),
    'Iran': ('Asia', 'Iranian Rial', 'IRR', '﷼'),
    'Iraq': ('Asia', 'Iraqi Dinar', 'IQD', 'ع.د'),
    'Ireland': ('Europe', 'European Euro', 'EUR', '€'),
    'Israel': ('Asia', 'Israeli New Sheqel', 'ILS', '₪'),
    'Italy': ('Europe', 'European Euro', 'EUR', '€'),
    'Jamaica': ('North America', 'Jamaican Dollar', 'JMD', 'J$'),
    'Japan': ('Asia', 'Japanese Yen', 'JPY', '¥'),
    'Jordan': ('Asia', 'Jordanian Dinar', 'JOD', 'د.ا'),
    'Kazakhstan': ('Europe', 'Kazakhstani Tenge', 'KZT', 'лв'),
    'Kenya': ('Africa', 'Kenyan Shilling', 'KES', 'KSh,'),
    'Kiribati': ('Australia and Oceania', 'Australian Dollar', 'AUD', '$'),
    'Kosovo': ('Europe', 'Euro', 'EUR', '€'),
    'Kuwait': ('Asia', 'Kuwaiti Dinar', 'KWD', 'د.ك'),
    'Kyrgyzstan': ('Asia', 'Kyrgyzstani Som', 'KGS', 'лв'),
    'Laos': ('Asia', 'Lao Kip', 'LAK', '₭'),
    'Latvia': ('Europe', 'Latvian Lats', 'LVL', 'Ls'),
    'Lebanon': ('Asia', 'Lebanese Pound', 'LBP', '£'),
    'Lesotho': ('Africa', 'Lesotho Loti', 'LSL', 'L'),
    'Liberia': ('Africa', 'Liberian Dollar', 'LRD', '$'),
    'Libya': ('Africa', 'Libyan Dinar', 'LYD', 'ل.د'),
    'Liechtenstein': ('Europe', 'Swiss Franc', 'CHF', 'CHF'),
    'Lithuania': ('Europe', 'Lithuanian Litas', 'LTL', 'Lt'),
    'Luxembourg': ('Europe', 'European Euro', 'EUR', '€'),
    'Macedonia': ('Europe', 'Macedonian Denar', 'MKD', 'ден'),
    'Madagascar': ('Africa', 'Malagasy Ariary', 'MGA', 'Ar'),
    'Malawi': ('Africa', 'Malawian Kwacha', 'MWK', 'MK'),
    'Malaysia': ('Asia', 'Malaysian Ringgit', 'MYR', 'RM'),
    'Maldives': ('Asia', 'Maldives Rufiyaa', 'MVR', 'Rf'),
    'Mali': ('Africa', 'West African CFA', 'XOF', 'CFA'),
    'Malta': ('Europe', 'Maltese Lira', 'MTL', '₤'),
    'Marshall Islands': ('Australia and Oceania',
                         'United States Dollar',
                         'USD',
                         '$'),
    'Mauritania': ('Africa', 'Mauritanian Ouguiya', 'MRO', 'UM'),
    'Mauritius': ('Africa', 'Mauritian Rupee', 'MUR', '₨'),
    'Mexico': ('North America', 'Mexican Peso', 'MXN', '$'),
    'Micronesia': ('Australia and Oceania', 'United States Dollar', 'USD', '$'),
    'Moldova': ('Europe', 'Moldovan Leu', 'MDL', 'L'),
    'Monaco': ('Europe', 'European Euro', 'EUR', '€'),
    'Mongolia': ('Asia', 'Mongolian Tugrik', 'MNT', '₮'),
    'Montenegro': ('Europe', 'European Euro', 'EUR', '€'),
    'Morocco': ('Africa', 'Moroccan Dirham', 'MAD', 'DH'),
    'Mozambique': ('Africa', 'Mozambican Metical', 'MZN', 'MT'),
    'Myanmar': ('Asia', 'Myanmar Kyat', 'MMK', 'K'),
    'Namibia': ('Africa', 'Namibian Dollar', 'NAD', '$'),
    'Nauru': ('Australia and Oceania', 'Australian Dollar', 'AUD', '$'),
    'Nepal': ('Asia', 'Nepalese Rupee', 'NPR', '₨'),
    'Netherlands': ('Europe', 'European Euro', 'EUR', '€'),
    'New Zealand': ('Australia and Oceania', 'New Zealand Dollar', 'NZD', '$'),
    'Nicaragua': ('North America', 'Nicaraguan Córdoba', 'NIO', 'C$'),
    'Niger': ('Africa', 'West African CFA', 'XOF', 'CFA'),
    'Nigeria': ('Africa', 'Nigerian Naira', 'NGN', '₦'),
    'North Korea': ('Asia', 'North Korean Won', 'KPW', '₩'),
    'Norway': ('Europe', 'Norwegian Krone', 'NOK', 'kr'),
    'Oman': ('Asia', 'Omani Rial', 'OMR', '﷼'),
    'Pakistan': ('Asia', 'Pakistan Rupee', 'PKR', '₨'),
    'Palau': ('Australia and Oceania', 'United States Dollar', 'USD', '$'),
    'Palestine': ('Asia', 'Jordanian Dinar', 'JOD', 'د.ا'),
    'Panama': ('North America', 'Panamanian Balboa', 'PAB', 'B/.'),
    'Papua New Guinea': ('Australia and Oceania',
                         'Papua New Guinea Kina',
                         'PGK',
                         'K'),
    'Paraguay': ('South America', 'Paraguay Guarani', 'PYG', 'Gs'),
    'Peru': ('South America', 'Peruvian Nuevo Sol', 'PEN', 'S/.'),
    'Philippines': ('Asia', 'Philippine Peso', 'PHP', '₱'),
    'Poland': ('Europe', 'Polish Zloty', 'PLN', 'zł'),
    'Portugal': ('Europe', 'European Euro', 'EUR', '€'),
    'Qatar': ('Asia', 'Qatari Riyal', 'QAR', '﷼'),
    'Republic Of The Congo': ('Africa', 'Central African CFA', 'XAF', 'FCFA'),
    'Romania': ('Europe', 'Romanian Leu', 'RON', 'lei'),
    'Russia': ('Europe', 'Russian Ruble', 'RUB', '₽'),
    'Rwanda': ('Africa', 'Rwandan Franc', 'RWF', 'FRw'),
    'Saint Kitts and Nevis': ('North America',
                              'East Caribbean Dollar',
                              'XCD',
                              '$'),
    'Saint Lucia': ('North America', 'East Caribbean Dollar', 'XCD', '$'),
    'Saint Vincent And The Grenadines': ('North America',
                                         'East Caribbean Dollar',
                                         'XCD',
                                         '$'),
    'Samoa': ('Australia and Oceania', 'Samoan Tala', 'WST', 'WS$'),
    'San Marino': ('Europe', 'European Euro', 'EUR', '€'),
    'Sao Tome And Principe': ('Africa', 'Sao Tome Dobra', 'STD', ' Db'),
    'Saudi Arabia': ('Asia', 'Saudi Arabian Riyal', 'SAR', '﷼'),
    'Senegal': ('Africa', 'West African CFA', 'XOF', 'CFA'),
    'Serbia': ('Europe', 'Serbian Dinar', 'RSD', 'Дин.'),
    'Seychelles': ('Africa', 'Seychelles Rupee', 'SCR', '₨'),
    'Sierra Leone': ('Africa', 'Sierra Leonean Leone', 'SLL', 'Le'),
    'Singapore': ('Asia', 'Singapore Dollar', 'SGD', '$'),
    'Slovakia': ('Europe', 'Slovak Koruna', 'SKK', 'Sk'),
    'Slovenia': ('Europe', 'European Euro', 'EUR', '€'),
    'Solomon Islands': ('Australia and Oceania',
                        'Solomon Islands Dollar',
                        'SBD',
                        '$'),
    'Somalia': ('Africa', 'Somali Shilling', 'SOS', 'S'),
    'South Africa': ('Africa', 'South African Rand', 'ZAR', 'R'),
    'South Korea': ('Asia', 'Korean Won', 'KRW', '₩'),
    'South Sudan': ('Africa', 'South Sudanese pound', 'SSP', '£'),
    'Spain': ('Europe', 'European Euro', 'EUR', '€'),
    'Sri Lanka': ('Asia', 'Sri Lankan Rupee', 'LKR', '₨'),
    'Sudan': ('Africa', 'Sudanese pound', 'SDG', 'SD'),
    'Suriname': ('South America', 'Suriname Dollar', 'SRD', '$'),
    'Sweden': ('Europe', 'Swedish Krona', 'SEK', 'kr'),
    'Switzerland': ('Europe', 'Swiss Franc', 'CHF', 'CHF'),
    'Syria': ('Asia', 'Syrian Pound', 'SYP', '£'),
    'Taiwan': ('Asia', 'New Taiwan Dollar', 'TWD', 'NT$'),
    'Tajikistan': ('Asia', 'Tajikistan Somoni', 'TJS', 'ЅM'),
    'Tanzania': ('Africa', 'Tanzanian Shilling', 'TZS', 'TSh'),
    'Thailand': ('Asia', 'Thai Baht', 'THB', '฿'),
    'Timor-Leste': ('Asia', 'United States Dollar', 'USD', '$'),
    'Togo': ('Africa', 'West African CFA', 'XOF', 'CFA'),
    'Tonga': ('Australia and Oceania', "Tongan Pa'Anga", 'TOP', 'T$'),
    'Trinidad And Tobago': ('North America',
                            'Trinidad and Tobago Dollar',
                            'TTD',
                            'TT$'),
    'Tunisia': ('Africa', 'Tunisian Dinar', 'TND', 'د.ت'),
    'Turkey': ('Europe', 'Turkish New Lira', 'TRY', '₺'),
    'Turkmenistan': ('Asia', 'Turkmenistani Manat', 'TMM', 'T'),
    'Tuvalu': ('Australia and Oceania', 'Australian Dollar', 'AUD', '$'),
    'Uganda': ('Africa', 'Ugandan Shilling', 'UGX', 'USh'),
    'Ukraine': ('Europe', 'Ukrainian Hryvnia', 'UAH', '₴'),
    'United Arab Emirates': ('Asia',
                             'United Arab Emirates Dirham',
                             'AED',
                             'د.إ'),
    'United Kingdom': ('Europe', 'United Kingdom Pound Sterling', 'GBP', '£'),
    'United States Of America': ('North America',
                                 'United States Dollar',
                                 'USD',
                                 '$'),
    'Uruguay': ('South America', 'Uruguayan peso', 'UYU', '$U'),
    'Uzbekistan': ('Asia', 'Uzbekistani Som', 'UZS', 'лв'),
    'Vanuatu': ('Australia and Oceania', 'Vanuatu Vatu', 'VUV', 'VT'),
    'Vatican City': ('Europe', 'European Euro', 'EUR', '€'),
    'Venezuela': ('South America', 'Venezuelan Bolivar', 'VEF', 'Bs'),
    'Vietnam': ('Asia', 'Viet Nam Dong', 'VND', '₫'),
    'Yemen': ('Asia', 'Yemeni Rial', 'YER', '﷼'),
    'Zambia': ('Africa', 'Zambian Kwacha', 'ZMK', 'ZK'),
    'Zimbabwe': ('Africa', 'Zimbabwean Dollar', 'ZWD', '$')
}
