# Generated by Django 2.2.20 on 2021-04-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_invoice', '0007_auto_20210427_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoice',
            name='state',
            field=models.CharField(choices=[('edited', 'édité'), ('pending', 'en attente'), ('sent', 'envoyé'), ('late', 'en retard'), ('paid', 'payé')], default='pending', max_length=255),
        ),
    ]
