# Generated by Django 2.2.20 on 2021-05-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_invoice', '0008_auto_20210427_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(),
        ),
    ]
