# Generated by Django 2.2.24 on 2021-07-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_invoice', '0010_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='gcs',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='term',
            name='org_logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='bank_bic',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='term',
            name='bank_iban',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='term',
            name='org_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='term',
            name='org_siret',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='term',
            name='org_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='term',
            name='org_vat_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='term',
            name='overdue',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='vat_rule',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
