name: Publish to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Set PBR_VERSION
        run: echo "PBR_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Build packages
        run: |
          python3 setup.py sdist

      - name: Publish mag-archiver
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
