
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-02T12:09:17+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "212520b139778e3d5be7d649756e076e0350e595",
 "version": "0.7.0.post.dev322"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
