
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-09T03:53:31+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9cfdb2482cc06f6b5eda7a1bedb0bdbc74e3a619",
 "version": "1.15.0.post.dev267"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
