
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-05T12:46:14-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2667dad8da4ae48be7f18d381352b800a995e5d0",
 "version": "v1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
