#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pymirror']

package_data = \
{'': ['*'], 'pymirror': ['data/*']}

entry_points = \
{'console_scripts': ['pymirror = pymirror.cli:main']}

setup(name='pymirror',
      version='0.1.8',
      description='pymirror',
      author=None,
      author_email='Alyetama <56323389+Alyetama@users.noreply.github.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      entry_points=entry_points,
     )
