[tool.poetry]
name = "AlekSIS-App-Resint"
version = "2.0a4"
packages = [
    { include = "aleksis" }
]
readme = "README.rst"
include = ["CHANGELOG.rst", "LICENCE.rst", "aleksis/**/*.mo"]

description = "AlekSIS (School Information System) — App Resint (Public poster)"
authors = [
   "Julian Leucker <leuckeju@katharineum.de>",
   "Frank Poetzsch-Heffter <p-h@katharineum.de>",
   "Jonathan Weth <dev@jonathanweth.de>"
]
license = "EUPL-1.2"
repository = "https://edugit.org/AlekSIS/onboarding/AlekSIS-App-Resint"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "Intended Audience :: Education",
    "Topic :: Education"
]

[[tool.poetry.source]]
name = "gitlab"
url = "https://edugit.org/api/v4/projects/461/packages/pypi/simple"
secondary = true

[tool.poetry.dependencies]
python = "^3.9"
AlekSIS-Core = "^2.0rc"

[tool.poetry.dev-dependencies]
aleksis-builddeps = "*"

[tool.poetry.plugins."aleksis.app"]
resint = "aleksis.apps.resint.apps:ResintConfig"

[tool.black]
line-length = 100
exclude = "/migrations/"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
