
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-03T06:43:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "817946761f969eabff6362073d05154b0d54cbde",
 "version": "1.0.27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
