# Version file autogenerated by the build process
version = '0.8.8rc4'
build = '700'
vcs_info = 'Git SHA1 29646d7b committed on 2021-08-06'

if __name__ == '__main__':
    print('KSCONF_VERSION="0.8.8rc4"\nKSCONF_BUILD="700"\nKSCONF_VCS_INFO="Git SHA1 29646d7b committed on 2021-08-06"')
