PREFIX_LENGTH = 3
MIN_LENGTH = 4
NUM_GROUPS = 64
PREFIXES = [
 'bid eps vit elo log dyi sad hug inq lim pal dut sud beh rat dec awa loo the',
 'pan gle cun irr lay dog ada cab civ yor sum tab dev doe sol hig wat han tha',
 'hed tos alp idl unh tig unk bul mag met roc set mee exa les ord ear fou wit',
 'ade nie dor tob liq iri amb abr hei moo sce sle tea fig fea wal tra hou thi',
 'osw jui amp gil atm mul avo bos iro anx son ton pat vis day amo ser pri whi',
 'vin jua toi oat dru bru dam nic sym sci leg gat opp rai dar let qui mus hav',
 'eme foe fet ech are bab yie pen mes joi bey jud mem nex any dif sam app fro',
 'vac hud tod gia lod ire tau way rin cli san fla che sel doo rel fol goo whe',
 'nai nan lei ora nur tid unf upp pul eur ran acr roa shi mou hol exc ove con',
 'bap sab gor ult oli rop may spl goe acq law mod bui joh inf hun tru fin wer',
 'dub ard sax cig isr tai apr pil gaz pag rul far she chu lin dre sur mak com',
 'cag fic tub ken rew mel bli sei hab edi bou ger mai cor pai lef mis bef cou',
 'jai fes unp orn utm ari tor siz inh lie pou kep pic suf kee sev fel mar tho',
 'sag gig sph lof usi aba jer put twi lab afr slo fie pol mas ste sup dea int',
 'inl adj evo swa duc rag mix rar jan ren sus ban rev sim cle foo sin car eve',
 'rad amm plu fer das van err tit med hos sis end woo evi eno eac clo bro pro',
 'tav sir mec nak lio egg dul cea ess ali jac els ene emp don lig tow min sai',
 'shr unj tay bag tie fon eat ant cel unl opi abl wes hum gla ple eng giv sho',
 'oxi byr heb vag aci ere inj ado cos deg new isl ben aff use can sec und wor',
 'got coi lot owe phe gos wag arc cus bon saf hat det boa uni cer fri gen wil',
 'buc awk ell cow loy jos wre flu ala smo hur inv por dur spi pow tre kin hea',
 'laz sau ecc rut xpa ham tee ner asi hid vil fil alr alt gir cap peo not som',
 'wok jef viv mic sov urg bol sak dav jou vir ten gon bus cre que tur bec mor',
 'oar sem jol ugl aud eco rej arg enc run din pop val smi tol wis las fac wou',
 'ina tax row joy and mex dig ash sic utt oug vic sca stu ful too mon des bee',
 'ded tun pot goa emi wra ete vai dai enj sep usu its ide mer hor rig dow you',
 'tok joa lew tyr cak ale kit obe sui coo anc rus pea tro arr act off rem for',
 'ivo inw wep rog gho vot hes lam fru lip blu req var qua ext ass gro cam wha',
 'aid elb alb ray hin asl doz clu dat fan sco lis obs dri los wri fat muc gre',
 'lem dei pia ara gli pay soi den typ fut dem sat swe spa wea inc ent chi sta',
 'big cup vul sme ava fit ave kis rui squ boy hen ric fur cit sub fai ind thr',
 'fid hir lux swu cut scr boi ign bis nin pau fif doc sch boo pur win spe pla',
 'jov arn aca dim ber fly hit jea apa fun lou eig vie all bla tal wom pas pre',
 'tec acu alf bin asp obv hot pus sno ven lib mid wro hon adv kne imp mos cha',
 'soa nel buf plo noo rif cof cot pit eag exe sli eit riv alm lor wen bet rea',
 'peg sku fad zea tin jap but tot mac swo rid unc rom pub sea hom lat lif tim',
 'yac awh lia wak dot vii awf fli try pet esc cho cir nor sil cau beg mea oth',
 'rit rip awo yon der bed emo own aun neg sac hil soc tog hop lar nam exp str',
 'oxe key luk xii nes jum rod cra jul kni bas tou pap twe eff alw hel nev abo',
 'dal nut sar ago lec loa deb mal nov swi has wid est ill mov poi tel yea par',
 'rug agn top ral abb bib abu gif cop bit get non sit nee fal cro als nat kno',
 'pav ety dos sie sna cry lev vas edg ves geo sug ros til cen unt eye rep per',
 'dip uns unn vig unu eli pip pin dol our gue gar bir war fra eas lan cal ver',
 'epo mau ses ges veg lun bad sty fem rap sof was def art spo lad nig pos fir',
 'dov isa sob atl jur pru rei ami fix inn lai nob exi dan dra reg sma sen see',
 'jup bak ela ske hoo env noi dwe jun roy doi men ang won mys sig roo sou lik',
 'kan thy now fen pov asc tex ast pun lak ski dau poe dep cla hap ope gra suc',
 'nil rub pep ine emb wol dom shu luc edu obt sla ris cur add cri liv bei dis',
 'cei sul exq ups voy dia lac cru gai sal phi coa aro dir occ sid rec aft',
 'hym vel ohi ama wed reb dus aug rol esp ori fas oft num arm ret bel lit',
 'mol orl gow abi apo yes cul yel vio gui maj gol lau dou ask ano bac lea',
 'ing rab kat wiv ack mut gal obl bal fis len imm ame dee flo cas acc sha',
 'rur dum twa pon vei ena nav phy vol sys equ pie his sor soo bre sti upo',
 'sex lut box xvi une eld dic lyi ita age agr abs nei ref how nea bea her',
 'fos jim jok jon feb ahe cav wei nar mur hus div spr ter goi hal col onl',
 'tue lil fed unw upw tom edw tes wav ann die glo fiv bur thu har jus man',
 'bew cod puz wir owi oce egy iss gam low ima tem bra nec mom wan fee mad',
 'fue gas cae rud wic nap tir god jes rob ani obj wai gav fam bes att aga',
 'haw gan nep agi nod aus gun pec duk tas out wee aut poo blo mot bri res',
 'onw ana ibi hau fev nos amu one pac bil sun cat bor gov rou bot mig wel',
 'enl ath upr oxf daw una bow poc six rac fav bar wif chr pra alo ins sto',
 'ach iot gul bun pup red old jew org gua kil cov adm bod tri mil him lon',
 'pho coc pio omi hee quo fau gri jam ble fle bat ele voi say mat fre tak',
 'iso imi pis mam phr oct mir exh yar loc hai dro sav del ans onc lov who',
]
