
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-04T13:01:27-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "824196b7863055816213e503bdb0934b8d5bfa4b",
 "version": "1.4.1rc8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
