
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-03T12:42:23-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e040888ba36dea7b9003b13f3af50fa619fca03e",
 "version": "2021.8.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
