
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-04T13:35:48+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "edceebef12c7bfc172417182f3ee8ceb1fbc8ef1",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
