
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-04T10:55:52-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "baaf016eed8f7570b5ac5753c7502fe7a2939a7c",
 "version": "2021.8.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
