# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Get all git tags
      run: git fetch --prune --unshallow --tags

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
        pip-sync

    - name: Test with pytest
      run: |
        flake8 .
        pytest --mypy

    - name: Build distributions
      run: |
        python setup.py sdist bdist_wheel

    - name: Deploy to PyPI
      env:
        PYPI_USER: ${{ secrets.PYPI_USER }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload --username "$PYPI_USER" --password "$PYPI_PASSWORD" dist/*
