
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-08T10:56:00+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "637d89f1937ef31f750735aae15e5f9436a9a1bb",
 "version": "0.8.13a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
