
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-05T12:13:33+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f9199ed5a1e091a30212f06b564f7b3060a62c51",
 "version": "v0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
