# Generated by Django 2.2.18 on 2021-02-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_invoice', '0005_auto_20210112_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'default_permissions': ['add', 'change', 'delete', 'view', 'control']},
        ),
        migrations.AlterModelOptions(
            name='customerinvoice',
            options={'default_permissions': ['add', 'change', 'delete', 'view', 'control']},
        ),
        migrations.AlterModelOptions(
            name='freelanceinvoice',
            options={'default_permissions': ['add', 'change', 'delete', 'view', 'control']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'default_permissions': ['add', 'change', 'delete', 'view', 'control']},
        ),
    ]
