# Generated by Django 2.2.24 on 2021-07-17 19:38

from django.db import migrations, models
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_invoice', '0009_auto_20210511_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlid', djangoldp.fields.LDPUrlField(blank=True, null=True, unique=True)),
                ('is_backlink', models.BooleanField(default=False, help_text='set automatically to indicate the Model is a backlink')),
                ('allow_create_backlink', models.BooleanField(default=True, help_text='set to False to disable backlink creation after Model save')),
                ('org_name', models.TextField()),
                ('org_address', models.TextField()),
                ('org_siret', models.TextField()),
                ('org_status', models.TextField()),
                ('org_vat_number', models.TextField()),
                ('vat_rule', models.TextField()),
                ('bank_bic', models.TextField()),
                ('bank_iban', models.TextField()),
                ('overdue', models.TextField()),
            ],
            options={
                'abstract': False,
                'default_permissions': ['add', 'change', 'delete', 'view', 'control'],
                'depth': 0,
                'anonymous_perms': ['view'],
                'authenticated_perms': ['inherit', 'add', 'change', 'delete'],
                'owner_perms': ['inherit', 'control'],
            },
        ),
    ]
