# Generated by Django 2.2.23 on 2021-07-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_invoice', '0011_auto_20210721_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoice',
            name='identifier',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='tvaRate',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='freelanceinvoice',
            name='freelanceFullname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='freelanceinvoice',
            name='htAmount',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='freelanceinvoice',
            name='identifier',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
