
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-09T17:59:23+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f2bfcabb1c60cf5b7a7e4851fb96258bc7c80a9d",
 "version": "0.3.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
