[tool.poetry]
name = "insee_number_translator"
version = "0.3.0"
description = "Translate french INSEE number to meaningful data"
authors = ["Gabriel Augendre <gabriel@augendre.info>"]
license = "MIT"
homepage = "https://git.augendre.info/gaugendre/insee_number_translator"
repository = "https://git.augendre.info/gaugendre/insee_number_translator"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pre-commit = "^2.13.0"

[tool.poetry.scripts]
insee = 'insee_number_translator.main:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ['py37']

[tool.isort]
profile = "black"
