[tool.poetry]
name = "fastel"
version = "1.1.4"
description = ""
authors = ["Chien <a0186163@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
fastapi = ">=0.63.0"
revjwt = "^1.0.4"
revdb = "^1.0.5"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
black = "^20.8b1"
isort = "^5.8.0"
autoflake = "^1.4"
mypy = "^0.812"
flake8 = "^3.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = 'black'