#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['ertai']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

setup(name='ertai',
      version='0.0.3',
      description='A tool for mathematical analysis of Magic the Gathering',
      author='Vincent Knight',
      author_email='vince@vknight.org',
      url='https://vknight.org',
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      python_requires='>=3.8',
     )
