
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-02T13:24:03+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b35fa46934264f8df484a8925f354d79e5be88c",
 "version": "0.7.0.post.dev336"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
