[tool.poetry]
name = "biopsykit"
version = "0.2.0"
description = "A python package for the analysis of biopsychological data."
authors = ["Robert Richer <robert.richer@fau.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
numpy = "^1"
pandas = "^1"
matplotlib = "^3"
seaborn = "^0.11.1"
neurokit2 = "^0.1.3"
pingouin = "^0.3.12"
IPython = "^7.13.0"
ipympl = "^0.7.0"
ipywidgets = "^7.6.3"
scipy = "^1.7.1"
statannot = "^0.2.3"
tqdm = "^4.62.0"
joblib = "^1.0.0"
scikit-learn = "^0.24.2"
nilspodlib = "^3.2.2"
openpyxl = "^3.0.7"
XlsxWriter = "^1.4.5"
mne = {version = "^0.23.0", optional = true}

[tool.poetry.extras]
mne = ["mne"]

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
pytest-cov = "^2.8.1"
prospector = "^1.2.0"
black = "^20.8b1"
sphinx = "^3.0.1"
numpydoc = "^1"
sphinx-gallery = "^0.8.2"
sphinx_issues = "^1.2.0"
pydata-sphinx-theme = "^0.6.2"
recommonmark = "^0.6.0"
coverage = "^4.5.4"
doit = "^0.32.0"
ipykernel = "^5.2.0"
memory_profiler = "^0.57.0"
toml = "^0.10.1"
mypy = "^0.790"
pytest-xdist = "^2.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py38']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | docs
    | build
    | dist
    | \.virtual_documents
  )/
)
'''
