
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-09T14:00:50-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "606b42b1f342917d8693fcb490546f58685e17c9",
 "version": "0.5.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
