[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool]
[tool.poetry]
authors = ["fab4key"]
description = "ConsoleLog.info(text) or error(text) or warning(text)"
name = "printloghelp"
version = "0.1.1"
[tool.poetry.dependencies]
python = "^3.8"
colorama = "^0.4.4"
[tool.poetry.dev-dependencies]
