[tool.poetry]
name = "console_debugger"
version = "0.1"
description = "Это подключаемая библиотека, для удобного вывода отладочной информации."
authors = ["Denis Kustov <denis-kustov@rambler.ru>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/denisxab/console_debugger"
repository = "https://github.com/denisxab/console_debugger"

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
