
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-08T17:25:29+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "72ec41dabaf4b702c38ac9971fe24c5ea15d16b6",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
