
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-05T16:49:02+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6de041ddfa2c0cb9a54689373fceb28fb903eff0",
 "version": "0.13.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
