
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-08T02:23:14+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bcbf21ec88dd95929b1d6439ebbf37b3cb266988",
 "version": "0.7.dev2132"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
