[tool.poetry]
name = "gitlab_errand_boy"
version = "0.1.12"
description = "Run errands with GitLab."
authors = ["Gleb Buzin <qufiwefefwoyn@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://gitlab.com/buzin.gb/gitlab_errand_boy"
repository = "https://gitlab.com/buzin.gb/gitlab_errand_boy"
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
requests = ">=2.0.0"
tenacity = ">=6.0.0"

[tool.poetry.dev-dependencies]
autoflake = ">=1.3.1"
black = ">=21.6b0"
flake8 = ">=3.7.9"
isort = ">=5.8.0"
mypy = ">=0.800"
pytest = ">=5.4.1"
pytest-cov = ">=2.8.1"
pytest-xdist = {extras = ["psutil"], version = ">=2.3.0"}
pytest-randomly = ">=3.8.0"
pre-commit = ">=2.13.0"
Faker = ">=8.8.1"
codespell = ">=2.1.0"
pydocstyle = ">=6.1.1"
types-requests = ">=0.1.13"
python-dotenv = ">=0.18.0"
ipykernel = ">=5.5.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.12"
version_files = [
    "gitlab_errand_boy/__version__.py",
    "pyproject.toml:version"
]
