# This file is generated by setup.py. DO NOT EDIT!

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

version = '1.10.1'
git_version = '1f63dcb7fcc3a8bf5c3c8e326867ecd6f5c43f35'
