
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-09T10:57:17-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e910f7ef5c67630f3847a7d524e4ce00d400bfae",
 "version": "v0.12.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
