[package]
name = "performance_modules"
version = "0.1.0"
edition = "2018"
authors = ["Taylor Parrish <taylor.parrish@avenue8.com>"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geojson = { version = "0.22.0", features = ["geo-types"] }
geo-types = "0.7.1"
geo = "0.17.1"
rayon = "1.5.0"
ndarray = "0.14.0"
pyo3 = "0.13.2"
serde_json="1.0.64"

[lib]
name = "mr_rogers"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]