
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-09T16:08:46+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a4773ed374ab0063b480713c0ded255fe6bf7d11",
 "version": "0.4.70"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
