
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-03T06:18:08+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "88e011e05cbd5ad83e95164ea6df90b97ae0ef90",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
