
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-06T14:58:34+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "79f16980711492f18246e4308748fe0afa6bdebe",
 "version": "1.0.40"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
