
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-03T08:14:56+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "97cf323b8c2ae9d8168aca9642a621c79db71ec7",
 "version": "v0.1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
