[tool.poetry]
name = "tex2tree"
version = "0.1.0"
description = ""
authors = ["赵文祺 <1027572886a@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
networkx = "^2.6.2"
matplotlib = "^3.4.2"
ply = "^3.11"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.7b0"
isort = "^5.9.3"
tqdm = "^4.62.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
