
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-09T17:29:27+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6f0483f9d18fa1a486205477b5a50e93d9dccbe7",
 "version": "0.3.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
