
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-08T10:42:10+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8f0c77b8dbfa44dd5f5390ca8226b78ba24e918d",
 "version": "0.8.13a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
