words = ["cherries",
         "garden",
         "pathetic",
         "perish",
         "cub",
         "lopsided",
         "rabid",
         "triumph",
         "humiliate",
         "strike",
         "hilarious",
         "wear",
         "shave",
         "manage",
         "relax",
         "grain",
         "convey",
         "guide",
         "wary",
         "earthy",
         "aquatic",
         "history",
         "dance",
         "tame",
         "hesitant",
         "secretary",
         "doll",
         "thoughtful",
         "silky",
         "experience",
         "cold",
         "deeply",
         "direct",
         "cheese",
         "regard",
         "evasive",
         "short",
         "muscle"]

another = ["try another letter: ",
           "guess again: ",
           "guess another letter: ",
           "try something else: ",
           "maybe a different letter: "]