
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-09T07:11:59-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "22be44233333146765d4b1f67e881e81f0d04b4a",
 "version": "v0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
