[tool.poetry]
name = "causalenv"
version = "0.1.1"
description = ""
authors = ["Elias Aoun Durand <elias.aoundurand@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
gym = "^0.18.0"
setuptools = "^57.0"
[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
