
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-11T04:22:10+0000",
 "dirty": true,
 "error": null,
 "full-revisionid": "2aa724636c3768a5977216516e3ccb755d63e82f",
 "version": "0.1.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
