language: python
os: linux

jobs:
  include:
    - name: "Linux, Python 3.8, required packages, codecov"
      python: 3.8
      env: CODECOV=TRUE
    - name: "Linux, Python 3.8, required packages, parallel"
      python: 3.8
    - name: "Linux, Python 3.8, required packages, serial"
      python: 3.8
      env: NUMBA_NUM_THREADS=1
    - name: "OSX, Python 3.8, required packages"
      language: shell
      os: osx
      before_install:
        - export PY_SFX=3
        - export HOMEBREW_NO_INSTALL_CLEANUP=1
        - export HOMEBREW_NO_AUTO_UPDATE=1

install:
  - |
    if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      export apt_get_install="sudo apt-get install --no-install-recommends"
      $apt_get_install ffmpeg || exit 1;
      export NUMBA_THREADING_LAYER=omp
    fi;
  - pip$PY_SFX install -U pytest-cov codecov
  - pip$PY_SFX install -U -r test-time-requirements.txt
  - pip$PY_SFX install -e .

script:
  - python$PY_SFX -m numba -s
  - |
    if [[ $CODECOV == 'TRUE' ]]; then
      python$PY_SFX -m pytest -We --cov-report term --cov=PyMPDATA PyMPDATA_tests || exit 1;
    else
      python$PY_SFX -m pytest -We PyMPDATA_tests || exit 1;
    fi;
  # execute Python lines from README.md
  - awk < README.md 'BEGIN {cmt=1; swp=0;} {swp=(substr($0,1,3)=="```"); if (swp && !cmt) {cmt=1; swp=0} if (cmt) print("#" $0); else print $0; if (swp && cmt) {cmt=0; swp=0}}' | python$PY_SFX

after_success:
  - |
    if [[ $CODECOV == 'TRUE' ]]; then
      codecov || exit 1;
    fi;
