[package]
name = "nlpo3-python"
version = "1.1.3"
edition = "2018"
license = "Apache-2.0"
authors = ["Thanathip Suntorntip Gorlph"]
description = "Python binding for nlpO3 Thai language processing library"
exclude = ["notebooks"]

[lib]
name = "_nlpo3_python_backend"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
ahash = "0.7.2"
lazy_static = "1.4.0"
nlpo3 = "1.2.0"

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]
