[tool.poetry]
name = "musamusa_fal"
version = "0.1.5"
description = "Use this package to store a filename and a line number."
authors = ["suizokukan <suizokukan@orange.fr>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.9"
rich = "^10.2.0"
iaswn = "^0.0.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
