
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-02T09:39:22-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "de8b150fd42a4869961fdd016b5e94d633742c13",
 "version": "1.1.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
