
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-04T03:39:23+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1c82dd3d494ee41ce350b151931682635486e585",
 "version": "1.15.0.post.dev253"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
