#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['fastdb']

package_data = \
{'': ['*']}

setup(name='fastdb',
      version='1.0.0',
      description='Faster database operations using Python',
      author=None,
      author_email='Sarmad Gulzar <sarmadgulzar@hotmail.com>',
      url=None,
      packages=packages,
      package_data=package_data,
     )
