
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-04T11:12:33-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3414d59929d4b7163cf552b1aeb2a473c49b2e20",
 "version": "2021.8.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
