[tool.poetry]
name = "jmanager"
version = "1.3.0"
description = "A lightweight Jupyter process manager"
authors = ["Yasunori Horikoshi <hotoku@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.6.2,<4"
click = "^8.0.1"
jupyterlab = "^3.1.4"

[tool.poetry.dev-dependencies]
bump2version = "^1.0.1"
wheel = "^0.36.2"
watchdog = "^2.1.3"
flake8 = "^3.9.2"
tox = "^3.24.1"
coverage = "^5.5"
Sphinx = "^4.1.2"
twine = "^3.4.2"

[tool.poetry.scripts]
jmanager = "jmanager.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
