
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-06T19:49:28-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2ee3ffe5ed918845f5f56f006755efd04774abd6",
 "version": "0.8.315"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
