
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-10T03:41:18+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "f2ca4012e9a58df83ccdcc9bb5d687293024364b",
 "version": "0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
