
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-07T17:33:03-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d469d99357a90dbc3224766e102c4a4ce3a65123",
 "version": "v0.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
