
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-02T17:28:06+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5b6bd5429f44d0a10dbdf5f941d7c22d95643a99",
 "version": "0.0.46"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
