
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-04T12:50:55+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d11c91aaa81c6034bdc42ce547823248acc05efb",
 "version": "v0.6.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
