
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-02T14:10:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8d3e2b1a4fac58823bdd2fd698fd15a7ddf381a5",
 "version": "2504"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
