
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-02T12:44:42+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "de6bad000f5294f64bd8f7465dbc2d96d4f04991",
 "version": "0.7.0.post.dev330"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
