
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-09T13:47:16-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "4bf1934487080fda36f742d55d1dc3ab6d80bae0",
 "version": "0.3.7.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
