[tool.poetry]
name = "building_plus"
version = "0.1.2"
description = "Dynamic building simulator based on EnergyPlus with enhancements."
authors = ["Dustin McLarty <dustin.mclarty@wsu.edu>"]
license = "MIT"
include = ["demo_files"]

[tool.poetry.dependencies]
python = "~3.8"
numpy = "^1.21.1"
scipy = "^1.7.0"
matplotlib = "^3.4.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
