#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pymirror']

package_data = \
{'': ['*'],
 'pymirror': ['.wdm/*',
              '.wdm/drivers/*',
              '.wdm/drivers/geckodriver/*',
              '.wdm/drivers/geckodriver/macos/*',
              '.wdm/drivers/geckodriver/macos/v0.29.1/*',
              'data/*']}

entry_points = \
{'console_scripts': ['pymirror = pymirror.cli:main']}

setup(name='pymirror',
      version='0.2.2',
      description='pymirror',
      author=None,
      author_email='Alyetama <56323389+Alyetama@users.noreply.github.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      entry_points=entry_points,
     )
