
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-04T12:38:56+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1d14d9ab42752306ebb70df41645dd623594698a",
 "version": "v0.6.4a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
