[tool.poetry]
name = "kaggle-downloader"
version = "1.0.0"
description = "Download kernels from Kaggle."
authors = ["Lars Reimann <mail@larsreimann.com>"]
license = "MIT"

[tool.poetry.scripts]
kaggle-downloader = 'kaggle_downloader.main:main'

[tool.poetry.dependencies]
python = "^3.9"
kaggle = "^1.5.12"
nbformat = "^5.1.3"
nbconvert = "^6.1.0"
jupyter = "^1.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
