
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-03T06:04:06+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "cfef207021bf18c003b1f451846cf97a01bb5b39",
 "version": "1.0.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
