
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-02T12:35:32+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2abf8777cc2da0885419a2c46c025759863f16d4",
 "version": "0.7.0.post.dev328"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
