
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-05T11:39:31+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "dac9e20b59d1559caa10f5ed969452e8832ce7f7",
 "version": "1.0.38"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
