
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-08T11:24:11+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a3fd7ce7d93c5d450ddb0400290bfffc8b9ed27b",
 "version": "0.8.13a8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
