
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-05T08:53:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f99cd4cb2280110a9d4a6c7e20daa334eb3a4b73",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
