
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-03T15:09:08+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "22b4cdac5b2bee4ba7b8c4fc28bf1f43b54cc915",
 "version": "1.0.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
