
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "3fe45661cd79c5137d9d4f5f4adb4d9519bc2084",
 "version": "1.7.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
