
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-05T11:31:53-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0ead7d21d743be3332303b893a06d6fb163a2de9",
 "version": "4.12.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
