dist: xenial
services:
  - docker
cache:
  directories:
    - ${HOME}/.cache
    - ${HOME}/cached-deps
    - ${HOME}/gopath/pkg/mod
    - "$(python3 -c 'import site; print(site.USER_BASE)')"
language: python
python:
  - "3.9"
  - "3.6"
env:
  global:
    - PATH=$HOME/cached-deps:$PATH
  jobs:
    # Most recent releases of the last two minor releases of Pachyderm
    - PACHYDERM_VERSION=1.12.5
    - PACHYDERM_VERSION=1.13.2

jobs:
  include:
    # other tests
    - python: 3.8
      env:
        - TOXENV=lint
        - PACHYDERM_VERSION=1.13.2
    - python: 3.8
      env:
        - TOXENV=examples
        - PACHYDERM_VERSION=1.13.2
install:
- make ci-install
before_script:
- make ci-setup
script:
- tox
after_script:
- etc/testing/kube_debug.sh

before_cache:
  # Make sure cache dirs have the necessary permissions for Travis to traverse
  # & copy them all elsewhere
  - proto/pachyderm/etc/testing/travis_cache.sh
