[tool.poetry]
name = "speedrun.py"
version = "21.8.0"
description = "An asynchronous API wrapper for speedrun.com"
authors = ["null2264"]

license = "MIT"
readme = "README.md"

packages = [
    { include = "speedrunpy" },
]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.6.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
