
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-02T13:01:59+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ec14cebdc436ed8c4bcfd2e00e2315aa6bf17193",
 "version": "0.7.0.post.dev334"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
