
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-10T17:57:37+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "c7747f489328b9a8741dbb1a823794d70ef4add8",
 "version": "2.6.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
