language: python
os: linux
dist: focal
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - sudo apt-get -y install pdftk texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-tests.txt
  - pip install -e .
  # Install DND latex styles
  - echo "$(kpsewhich -var-value TEXMFHOME)/tex/latex/"
  - mkdir -p "$(kpsewhich -var-value TEXMFHOME)/tex/latex/"
  - git clone https://github.com/rpgtex/DND-5e-LaTeX-Template.git "$(kpsewhich -var-value TEXMFHOME)/tex/latex/dnd"
# command to run tests
script:
  - pytest --cov=dungeonsheets tests/
  - flake8 dungeonsheets/ --exit-zero
  - cd examples/
  - makesheets --debug
  - makesheets --debug --fancy
  - makesheets --debug --output-format=epub
  - cd ../
after_success:
  - coveralls