[tool.poetry]
name = "insee_number_translator"
version = "0.2.0"
description = "Translate french INSEE number to meaningful data"
authors = ["Gabriel Augendre <gabriel@augendre.info>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pre-commit = "^2.13.0"

[tool.poetry.scripts]
insee = 'insee_number_translator.main:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ['py39']

[tool.isort]
profile = "black"
