
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-05T08:15:49-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "caa2a6fc44bd9364f121509fd6782df92299ee24",
 "version": "v0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
