
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-11T02:11:25+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "39edf67f7eda6bdd30bc102f8957ac74c67b4d01",
 "version": "0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
