
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-05T15:02:14-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "95f80c110314ab20eacc2ddbcf2868cd9295a319",
 "version": "5.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
