
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-04T07:36:43-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "466528dbcc0d2e7fc5359795af517c46517d00b5",
 "version": "v1.2.0a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
