
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-05T05:11:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6190541a82c2c4536a345e4043fa8abb705a9e0f",
 "version": "0.0.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
