
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-05T03:41:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "93338e969a2e5866adb73143e95879c35b2b31be",
 "version": "1.15.0.post.dev257"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
