
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-09T16:52:46+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8143b5b52bb788ef1082ae70181138d0297efd1c",
 "version": "0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
