
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-06T22:19:32+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0150b0c3bb92280d41ae7f67a5066b1ce1bee053",
 "version": "v0.1.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
