
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-02T11:48:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "81300f4710e63354800d9ce9c0b227d778290b76",
 "version": "0.7.0.post.dev318"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
