[tool.poetry]
name = "oarepo-model-builder"
version = "0.1.7"
description = "An utility library that generates OARepo required data model files from a JSON specification file"
authors = ["Miroslav Bauer <bauer@cesnet.cz>"]
readme = "README.md"

packages = [
    { include = "oarepo_model_builder" }
]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
json5 = "^0.9.6"
deepmerge = "^0.3.0"
libcst = "^0.3.19"
munch = "^2.4.0"
click = ">=7.1"
tomlkit = "^0.7.2"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."oarepo_model_builder.source"]
datamodel = "oarepo_model_builder.builders:DataModelBuilder"

[tool.poetry.plugins."oarepo_model_builder.elements"]
jsonschema = "oarepo_model_builder.builders:JSONSchemaBuilder"
mapping = "oarepo_model_builder.builders:MappingBuilder"

[tool.poetry.plugins."oarepo_model_builder.jsonschema"]
jsonschema = "oarepo_model_builder.outputs:JsonSchemaOutput"

[tool.poetry.plugins."oarepo_model_builder.mapping"]
mapping = "oarepo_model_builder.outputs:MappingOutput"

[tool.poetry.scripts]
models = "oarepo_model_builder.cli:model"
