
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-03T15:45:41+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4dc7e36118ba5b4d076aabf09a8111e41b46f0da",
 "version": "1.0.32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
