
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-22T16:56:38-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "881181607925b261969041597f5b0a98890badb4",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
