
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-02T17:14:38+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e11c3bdb5d59b2a4e15bc7938940353a045e017",
 "version": "v0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
