[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "celery",
    "kombu",
    "pydantic",
    "typing",
    "psycopg2",
    "requests",
    "pathlib"
]
build-backend = "setuptools.build_meta"