
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-06T14:12:11-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "f84887742b0dc8721aa7caa99b063feb04292904",
 "version": "v3.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
