[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "confluent-avro>=1.8.0",
    "confluent-kafka>=1.6.1",
    "fastavro>=1.4.4",
    "requests>=2.26.0",
    "jsonschema>=3.2.0",
    "pytz>=2021.1"
]
build-backend = "setuptools.build_meta"
