
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-09T03:30:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e5f0bdbb57140719fc6835a14f61dd1b32b80ddf",
 "version": "1.15.0.post.dev265"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
