
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-10T13:57:25+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "91813414141a7fb7ab73bbacd68238c8176b99ab",
 "version": "0.2.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
