
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-06T08:45:34+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "f1ec18c3d2fed4c9be4b9b12ee9a70de24aa4bdc",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
