CREATE OR REPLACE VIEW imessage_current.attachment_full_history_vw AS

 SELECT map.attachment_uid,
    a."ROWID",
    a.guid,
    'imessage_current'::text AS source,
    a.created_date,
    a.start_date,
    a.filename,
    a.uti,
    a.mime_type,
    a.transfer_state,
    a.is_outgoing,
    a.user_info,
    a.transfer_name,
    a.total_bytes,
    a.is_sticker,
    a.sticker_user_info,
    a.attribution_info,
    a.hide_attachment,
    a.ck_sync_state,
    a.ck_server_change_token_blob,
    a.ck_record_id,
    a.original_guid,
    a.sr_ck_sync_state,
    a.sr_ck_server_change_token_blob,
    a.sr_ck_record_id
   FROM imessage_current.attachment a
     LEFT JOIN imessage_current.map_attachment_id map ON a."ROWID" = map."ROWID" AND map.source::text = 'imessage_current'::text
UNION
 SELECT map.attachment_uid,
    a."ROWID",
    a.guid,
    'imessage_20191126'::text AS source,
    a.created_date,
    a.start_date,
    a.filename,
    a.uti,
    a.mime_type,
    a.transfer_state,
    a.is_outgoing,
    a.user_info,
    a.transfer_name,
    a.total_bytes,
    a.is_sticker,
    a.sticker_user_info,
    a.attribution_info,
    a.hide_attachment,
    a.ck_sync_state,
    a.ck_server_change_token_blob,
    a.ck_record_id,
    a.original_guid,
    a.sr_ck_sync_state,
    a.sr_ck_server_change_token_blob,
    a.sr_ck_record_id
   FROM imessage_historical.attachment_20191126 a
     LEFT JOIN imessage_current.map_attachment_id map ON a."ROWID" = map."ROWID" AND map.source::text = 'imessage_20191126'::text
UNION
 SELECT map.attachment_uid,
    a."ROWID",
    a.guid,
    'imessage_20171001'::text AS source,
    a.created_date,
    a.start_date,
    a.filename,
    a.uti,
    a.mime_type,
    a.transfer_state,
    a.is_outgoing,
    a.user_info,
    a.transfer_name,
    a.total_bytes,
    a.is_sticker,
    a.sticker_user_info,
    a.attribution_info,
    a.hide_attachment,
    NULL::bigint AS ck_sync_state,
    NULL::text AS ck_server_change_token_blob,
    NULL::text AS ck_record_id,
    NULL::text AS original_guid,
    NULL::bigint AS sr_ck_sync_state,
    NULL::text AS sr_ck_server_change_token_blob,
    NULL::text AS sr_ck_record_id
   FROM imessage_historical.attachment_20171001 a
     LEFT JOIN imessage_current.map_attachment_id map ON a."ROWID" = map."ROWID" AND map.source::text = 'imessage_20171001'::text
  ORDER BY 4 DESC;