CREATE OR REPLACE VIEW imessage_current.chat_full_history_vw AS

 SELECT map.chat_uid,
    c."ROWID",
    'imessage_current'::text AS source,
    c.guid,
    c.style,
    c.state,
    c.account_id,
    c.properties,
    c.chat_identifier,
    c.service_name,
    c.room_name,
    c.account_login,
    c.is_archived,
    c.last_addressed_handle,
    c.display_name,
    c.group_id,
    c.is_filtered,
    c.successful_query,
    c.engram_id,
    c.server_change_token,
    c.ck_sync_state,
    c.original_group_id,
    c.last_read_message_timestamp,
    c.sr_server_change_token,
    c.sr_ck_sync_state,
    c.cloudkit_record_id,
    c.sr_cloudkit_record_id,
    c.last_addressed_sim_id,
    c.is_blackholed
   FROM imessage_current.chat c
     JOIN imessage_current.map_chat_id map ON c."ROWID" = map."ROWID" AND map.source::text = 'imessage_current'::text
UNION
 SELECT map.chat_uid,
    c."ROWID",
    'imessage_20191126'::text AS source,
    c.guid,
    c.style,
    c.state,
    c.account_id,
    c.properties,
    c.chat_identifier,
    c.service_name,
    c.room_name,
    c.account_login,
    c.is_archived,
    c.last_addressed_handle,
    c.display_name,
    c.group_id,
    c.is_filtered,
    c.successful_query,
    c.engram_id,
    c.server_change_token,
    c.ck_sync_state,
    c.original_group_id,
    c.last_read_message_timestamp,
    c.sr_server_change_token,
    c.sr_ck_sync_state,
    c.cloudkit_record_id,
    c.sr_cloudkit_record_id,
    c.last_addressed_sim_id,
    c.is_blackholed
   FROM imessage_historical.chat_20191126 c
     JOIN imessage_current.map_chat_id map ON c."ROWID" = map."ROWID" AND map.source::text = 'imessage_20191126'::text
UNION
 SELECT map.chat_uid,
    c."ROWID",
    'imessage_20171001'::text AS source,
    c.guid,
    c.style,
    c.state,
    c.account_id,
    c.properties,
    c.chat_identifier,
    c.service_name,
    c.room_name,
    c.account_login,
    c.is_archived,
    c.last_addressed_handle,
    c.display_name,
    c.group_id,
    c.is_filtered,
    c.successful_query,
    NULL::text AS engram_id,
    NULL::text AS server_change_token,
    NULL::bigint AS ck_sync_state,
    NULL::text AS original_group_id,
    NULL::bigint AS last_read_message_timestamp,
    NULL::text AS sr_server_change_token,
    NULL::bigint AS sr_ck_sync_state,
    NULL::text AS cloudkit_record_id,
    NULL::text AS sr_cloudkit_record_id,
    NULL::text AS last_addressed_sim_id,
    NULL::bigint AS is_blackholed
   FROM imessage_historical.chat_20171001 c
     JOIN imessage_current.map_chat_id map ON c."ROWID" = map."ROWID" AND map.source::text = 'imessage_20171001'::text
  ORDER BY 3 DESC, 2 DESC;