[tool.poetry]
name = "pelican_precompress"
version = "2.1.0"
description = "Pre-compress your Pelican site using gzip, zopfli, and brotli!"
authors = ["Kurt McKee <contactme@kurtmckee.org>"]
license = "MIT"
packages = [
    { include = "pelican", from = "src" }
]
readme = "README.rst"
repository = "https://github.com/kurtmckee/pelican_precompress/"
keywords = ["pelican", "plugin", "gzip", "brotli", "zopfli"]
classifiers = [
    "Framework :: Pelican :: Plugins",
    "Development Status :: 5 - Production/Stable",
]

[tool.poetry.dependencies]
python = ">=3.6.1,<4.0"
pelican-granular-signals = "^1.0.0"

[tool.poetry.dev-dependencies]
tox = "^3.23.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.tox]
legacy_tox_ini = """

[tox]
envlist = clean, py{36, 37, 38, 39}-{brotli, }-{zopfli, }, report
skip_missing_interpreters = True
isolated_build = True


[testenv]
deps =
    blinker
    pytest
    pytest-cov
    pyfakefs
    brotli: brotli
    zopfli: zopfli
setenv =
    COVERAGE_FILE={toxworkdir}/.coverage.envname.{envname}
commands = {envpython} -m pytest --color=yes --cov=pelican.plugins.precompress --cov=test_pelican_precompress --cov-report=term tests/


[testenv:clean]
skip_install = True
deps =
    coverage[toml]
setenv =
    COVERAGE_FILE={toxworkdir}/.coverage
commands =
    {envpython} -m coverage erase


[testenv:report]
skip_install = True
deps =
    coverage[toml]
setenv =
    COVERAGE_FILE={toxworkdir}/.coverage
commands =
    {envpython} -m coverage combine
    {envpython} -m coverage report
    {envpython} -m coverage html

"""


[tool.coverage.run]
branch = true


[tool.coverage.paths]
source = [
    "src",
    "*/site-packages",
]
