[tool.poetry]
name = "test_poetry99"
version = "0.1.0"
description = ""
authors = ["yefei <fei_ye@hxecloud.com>"]

[tool.poetry.dependencies]
python = "^3.7"
Flask = "^2.0.1"
gunicorn = "^20.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
