
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-04T11:24:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "77ed89f718dd64da8fb070b25aa708ff307180f1",
 "version": "2506"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
