
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-04T07:41:41-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "f8cea032b758295a93e8809a84a7e6c8d12cdd93",
 "version": "0.6.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
