#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='notagain',
      version='0.3',
      description='Memory and disk cache for functions',
      author='Matías Battocchia',
      author_email='battox@gmail.com',
      url='https://github.com/matiasbattocchia/notagain',
      py_modules=['notagain'],
     )
