
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-03T18:11:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e1c8909d934333480ab8964ab94890933b26d56",
 "version": "0.4.32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
