[tool.poetry]
name = "firstappqjy"
version = "0.1.1"
description = ""
authors = ["SoftJing1 <118010248@link.cuhk.edu.cn>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
wow = 'entry:main'