[tool.poetry]
name = "compile-graph"
version = "0.1.3"
description = "Interactive graph to demonstrate stages of compilation"
authors = ["Kevin Lai <zlnh4@umsystem.edu>"]
license = "GPL"

[tool.poetry.dependencies]
python = "^3.8"
graphviz = "^0.17"
watchdog = "^2.1.3"
docopt = "^0.6.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
compile-graph = "compile_graph.compile_graph:main"
