apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: stressng-pod
  namespace: {{ namespace }}
spec:
  system_metrics:
    collection: false
    prom_url: ""
    es_url: "{{ url }}"
    prom_token: ""
    metrics_profile: ""
  elasticsearch:
    url: "{{ url }}"
    index_name: {{ index_name_pod }}
  metadata:
    collection: false
  workload:
    name: stressng
    args:
      pin: {{ pin }} # enable for nodeSelector
      pin_node: "{{ pin_node }}"
      resources: {{ resources }} # enable for resources requests/limits
      requests_cpu: 200m
      requests_memory: 100Mi
      limits_cpu: {{ limits_cpu }}
      limits_memory: {{ limits_memory_GB }}Gi
      # general options
      runtype: "{{ runtype }}"
      timeout: "{{ timeout }}"
      instances: {{ instances }}
      # cpu stressor options
      cpu_stressors: "{{ cpu_stressors }}"
      cpu_percentage: "{{ cpu_percentage }}"
      # vm stressor option
      vm_stressors: "{{ vm_stressors }}"
      vm_bytes: "{{ vm_bytes }}"
      # mem stressor options
      mem_stressors: "{{ mem_stressors }}"
