
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-05T09:24:10+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "361209e7027dea39eac1f7eaa79bd0e7b8cabf32",
 "version": "2507"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
