
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-09T13:25:59-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "278cb95cf4a6734d86599aa067eaa83750c620a5",
 "version": "0.0.16.post2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
