
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-09T13:40:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "78a2a11a171efacfca7b1cf6fd11d9bd5d6a8a52",
 "version": "0.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
