
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.54.0rc3'
version_full = 'c7d5f684ab93bd845d34fc2c6e9532d46985cc8a'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

