
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-08T22:08:15+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c471a98f9d859ea403d8b012f1ef2163237e736c",
 "version": "2021.08.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
