
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-06T15:30:52-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "eff542712cceb2972c427ecc54e33b5916c6ede8",
 "version": "0.4.0-rc.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
