[tool.poetry]
name = "graia-saya"
version = "0.0.10"
description = ""
authors = ["GreyElaina <31543961+GreyElaina@users.noreply.github.com>"]
license = "MIT"
packages = [
    { include = "graia", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.7"
graia-broadcast = ">=0.7.0"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]
black = "^20.8b1"

[tool.poetry.extras]
scheduler = ["graia-scheduler"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
