#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['sphinx_godot_theme']

package_data = \
{'': ['*'],
 'sphinx_godot_theme': ['static/*',
                        'static/css/*',
                        'static/js/*',
                        'templates/*']}

install_requires = \
['sphinx                    >= 4.1.2, < 5',
 'sphinx-tabs               >= 3.2.0, < 4',
 'recommonmark              >= 0.7.1, < 1',
 'sphinx-rtd-theme          >= 0.5.2, < 1',
 'sphinxext-opengraph       >= 0.4.2, < 1',
 'sphinx-notfound-page      >= 0.7.1, < 1',
 'readthedocs-sphinx-search >= 0.1.0, < 1']

extras_require = \
{'dev': ['pip        >= 21.2.2, < 22',
         'flit       >= 3.3.0,  < 4',
         'twine      >= 3.4.2,  < 4',
         'wheel      >= 0.36.2, < 1',
         'invoke     >= 1.6.0,  < 2',
         'setuptools >= 57.4.0, < 58'],
 'doc': ['sphinx'],
 'test': ['pytest']}

setup(name='sphinx-godot-theme',
      version='0.3.1',
      description='Standalone sphinx theme based on the official Godot documentation theme.',
      author=None,
      author_email='Arkadiusz Michał Ryś <Arkadiusz.Michal.Rys@gmail.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.8',
     )
