[tool.poetry]
name = "cst_geometry"
version = "0.0.6"
description = "Package for modelling in CST Microwave studio using python"
authors = ["konstantgr <60608301+konstantgr@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.21.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
