
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-10T16:17:07+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "cbc7c5e83bcc63e649688f8c31eb7436583b239a",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
