[tool.poetry]
name = "mongodm"
version = "0.1.0"
description = "Simple ODM for MongoDB"
authors = ["Deni <azureswastika@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/azureswastika/mongodm"
repository = "https://github.com/azureswastika/mongodm"
keywords = ["odm", "mongo", "mongodb"]
classifiers = [
    "Development Status :: 1 - Planning",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Database",
    "Typing :: Typed"
]
include = ["LICENSE",]

[tool.poetry.dependencies]
python = "^3.9"
pymongo = "^3.12.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"
black = "^21.7b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
issues = "https://github.com/azureswastika/mongodm/issues"