
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-03T19:26:33-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f1a7db84b4776af5357641cbbe547043cb4ff4ce",
 "version": "2021.8.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
