[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "qtile-window-trashbin"
authors = [{name = "Paul Hoffmann", email = "phfn@phfn.de"}]
readme = "README.md"
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]
dynamic = ["version", "description"]

[tool.flit.module]
name = "trashbin"

[project.urls]
Source = "https://github.com/phfn/qtile-window-trashbin"
Home = "https://phfn.de"
