#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

package_dir = \
{'': 'src'}

setup(name='qtile-window-trashbin',
      version='0.0.2',
      description='A thrashbin for qtile windows.',
      author=None,
      author_email='Paul Hoffmann <phfn@phfn.de>',
      url=None,
      py_modules=['trashbin'],
      package_dir=package_dir,
     )
