#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['traffic_generation_utils', 'traffic_generation_utils.monitoring_engines']

package_data = \
{'': ['*']}

setup(name='traffic_generation_utils',
      version='0.0.1',
      description='General set of utils to generate network traffic',
      author=None,
      author_email='Daniel Perdices <daniel.perdices@uam.es>',
      url=None,
      packages=packages,
      package_data=package_data,
     )
