
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-03T16:21:50+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c04209dbedf57506227ea73c49df6e45f2029d3c",
 "version": "1.0.33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
