[tool.poetry]
name = "coingecko-api-client"
version = "0.1.5"
description = "Unofficial CoinGecko API client based on HTTPX"
authors = ["Eugene Serdyuk <eugene.serdyuk@pm.me>"]
license = "MIT License"
readme = "README.md"
repository = "https://github.com/eserdk/coingecko-api-client"
keywords = ["coingecko", "api", "client", "crypto"]
classifiers = [
    'Development Status :: 2 - Pre-Alpha',
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3 :: Only",
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    "Operating System :: OS Independent",
]
include = ["LICENSE"]
packages = [
    {include = "coingecko_api_client", from = "src"}
]

[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.18.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
respx = "^0.17.1"
black = "^21.7b0"
isort = "^5.9.3"
flake8 = "^3.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
