
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-03T19:08:21-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b72c7a1fb9759aed78db6b322c67c09d95eaddb4",
 "version": "2021.8.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
