
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-08T15:07:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6df281e41f0fe52034a9102b3e1f0ec538748181",
 "version": "0.8.13a10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
