
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-06T08:13:12+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "051ecbf29c2a51923f5a83d177abfd50aedf54a4",
 "version": "0.22.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
