
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-04T05:30:01+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e72b557079ab6be598de8bd7e92418c8c83121a6",
 "version": "1.0.35"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
