
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-03T14:09:39+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c8802e5c4f20557b674ef3d724985d40b5ff0537",
 "version": "0.18.0b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
