#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['avss']

package_data = \
{'': ['*'], 'avss': ['scripts/*']}

entry_points = \
{'console_scripts': ['start_server = scripts:start_server']}

setup(name='avss',
      version='0.0.2',
      description='This is a test.',
      author=None,
      author_email='Victor Krook <victorkrook96@gmail.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      entry_points=entry_points,
     )
