
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-09T12:12:21-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "6490de23b3b47051947e621a0680ac92c24afa83",
 "version": "1.11.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
