
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-05T15:03:12-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "5402361b6c2f6a4764f51a6caac611cc7b375c38",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
