
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-02T12:15:28+0000",
 "dirty": true,
 "error": null,
 "full-revisionid": "f660409f3866f3a95a19bb3c327383aad41ad750",
 "version": "0.1.8.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
