# Version file autogenerated by the build process
version = '0.8.8rc3'
build = '697'
vcs_info = 'Git SHA1 d5ae0e0a committed on 2021-08-05'

if __name__ == '__main__':
    print('KSCONF_VERSION="0.8.8rc3"\nKSCONF_BUILD="697"\nKSCONF_VCS_INFO="Git SHA1 d5ae0e0a committed on 2021-08-05"')
