
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-03T06:09:15+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5b99859df36ba9b9293085aa782c5ae0937c22a3",
 "version": "1.0.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
